// Anti-drift guard: `all-projects.json` is hand-committed (not regenerated by `pnpm generate`) so fixture builds never couple to real project content, and this test is what catches it drifting out of sync with its source .md files.
import { expect, test } from "vitest";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "../../../../..");
const FIXTURES_PROJECTS_DIR = join(ROOT, "src/features/repositories/tests/ui/support/repositories");
const FIXTURES_ALL_PROJECTS_JSON = join(ROOT, "src/features/repositories/tests/ui/support/repos/all-projects.json");

interface RepoFile {
  path: string;
  lines: string[];
}
interface RepoIndex {
  name: string;
  files: RepoFile[];
}

/** Mirrors `generateAllProjectsIndex()` from scripts/generate.mjs; kept as a local copy since that script isn't built to be imported by tests. */
function buildAllProjectsIndex(srcDir: string): RepoIndex {
  const files: RepoFile[] = [];
  for (const entry of readdirSync(srcDir)) {
    if (!entry.endsWith(".md")) continue;
    const full = join(srcDir, entry);
    if (!statSync(full).isFile()) continue;
    const content = readFileSync(full, "utf8");
    files.push({ path: entry, lines: content.split("\n") });
  }
  files.sort((a, b) => a.path.localeCompare(b.path));
  return { name: "all-projects", files };
}

test("src/features/repositories/tests/ui/support/repos/all-projects.json exactly matches an index freshly built from src/features/repositories/tests/ui/support/repositories/*.md", () => {
  const expected = buildAllProjectsIndex(FIXTURES_PROJECTS_DIR);
  const committed = JSON.parse(readFileSync(FIXTURES_ALL_PROJECTS_JSON, "utf8")) as RepoIndex;
  expect(committed, "src/features/repositories/tests/ui/support/repos/all-projects.json is stale — regenerate it from src/features/repositories/tests/ui/support/repositories/*.md (see README's " +
      '"all-projects fixture" section) after editing any fixture project markdown file').toEqual(expected);
});

test("the fixture all-projects index is non-empty and every file has non-trivial content", () => {
  const index = buildAllProjectsIndex(FIXTURES_PROJECTS_DIR);
  expect(index.files.length > 0, "expected at least one fixture project .md file").toBeTruthy();
  for (const file of index.files) {
    expect(file.path.endsWith(".md"), `${file.path} should be a markdown file`).toBeTruthy();
    expect(file.lines.length > 1, `${file.path} should have more than one line`).toBeTruthy();
  }
});
