// View-id plumbing shared by the router pages and Terminal.svelte. Not
// copy — these are internal identifiers (route paths, dashboard.yaml menu
// ids, site.yaml status-bar window ids), never rendered as text directly.
export type ViewId = "home" | "builds" | "personnel" | "retina-v" | "profile";

/** Route path for each view id — used for pushState + popstate parsing. */
export const VIEW_ROUTES: Record<ViewId, string> = {
  home: "/",
  builds: "/builds",
  personnel: "/personnel",
  "retina-v": "/retina-v",
  profile: "/profile",
};

/**
 * dashboard.yaml menu rows use the prototype's original ids
 * (projects/xp/info/tracker — Homepage.dc.html `keys`/`labels`); the
 * status-bar window list (site.yaml) and our routes use the plainer
 * builds/personnel/profile/retina-v ids. This is the one place the two
 * vocabularies meet.
 */
const MENU_ID_TO_VIEW: Record<string, ViewId> = {
  projects: "builds",
  xp: "personnel",
  info: "profile",
  tracker: "retina-v",
};

export function menuIdToView(menuId: string): ViewId | undefined {
  return MENU_ID_TO_VIEW[menuId];
}

/** Global dashboard hotkeys (only active from the "home" view). */
const HOTKEY_TO_VIEW: Record<string, ViewId> = {
  b: "builds",
  p: "builds",
  x: "personnel",
  i: "profile",
  t: "retina-v",
};

export function hotkeyToView(key: string): ViewId | undefined {
  return HOTKEY_TO_VIEW[key];
}

export function pathToView(pathname: string): ViewId {
  const entry = (Object.entries(VIEW_ROUTES) as [ViewId, string][]).find(
    ([, path]) => path === pathname,
  );
  return entry ? entry[0] : "home";
}

/** Which status-bar window id (site.yaml) is active for a given view. */
export function activeWindowId(view: ViewId): string {
  return view === "home" ? "builds" : view;
}

/**
 * Grep overlay Enter-routing (PLAN.md Phase 8 item 3, porting
 * Component.grepOpenRow()'s path->view regex, Homepage.dc.html lines
 * 875-878). Real-index paths (generated by scripts/generate.mjs) are
 * checked first, exactly per the plan's mapping:
 *   content/personnel|Personnel.svelte -> personnel
 *   content/projects|Builds.svelte     -> builds
 *   TrackerView.svelte|Wallpaper.svelte -> retina-v
 *   Profile.svelte                     -> profile
 *   else                               -> null (close only, no navigation)
 *
 * PLAN.md Phase 9 verify flag (from Phase 8's verifier): the original port
 * used bare, unanchored substring alternates for fixture fidelity —
 * `/xp|Yazi/i`, `/projects|Lazygit/i`, `/Tracker|Wallpaper|subjects|Radar/i`,
 * `/Profile|info/i` — which would silently mis-route a *future* real path
 * that happens to contain one of those words anywhere (e.g. a hypothetical
 * `src/lib/info.ts` matching the bare `/info/i`, or a personnel-adjacent
 * `src/lib/xp-utils.ts` matching `/xp/i`). Tightened below: the real-index
 * rules are segment-anchored to the exact file/dir names scripts/
 * generate.mjs actually produces, so they can only ever match the specific
 * components/content directories named above, not an incidental substring.
 *
 * The prototype's own fixture-style paths (fixtures/grep-index.json, used
 * only by the visual-regression recipes, which never press Enter — see
 * that file's own paths: src/pages/xp.astro, src/pages/projects.astro,
 * src/components/Tracker.svelte, src/components/Radar.svelte, src/content/
 * xp/*.md) use the prototype's original bare-word vocabulary instead. That
 * fallback is gated to paths OUTSIDE src/ and tests/ — every fixture path
 * above lives under src/, so this fallback is unreachable for any of them
 * (fixture Enter-routing already has zero test coverage per the file
 * header this replaces; this file's own root-level fixture entries like
 * README.md/package.json/astro.config.mjs don't match the legacy words
 * either, so the fallback is effectively inert dead code, kept only for
 * prototype-regex fidelity) — the real rules above always run first and
 * unconditionally own everything under src/ and tests/, so no future real
 * file added there can ever fall through to the bare-word fallback.
 */
export function grepPathToView(path: string): ViewId | null {
  if (/(^|\/)content\/personnel\/|(^|\/)Personnel\.svelte$/.test(path)) return "personnel";
  if (/(^|\/)content\/projects\/|(^|\/)Builds\.svelte$/.test(path)) return "builds";
  if (/(^|\/)(TrackerView|Wallpaper)\.svelte$/.test(path)) return "retina-v";
  if (/(^|\/)Profile\.svelte$/.test(path)) return "profile";

  if (!/^(src|tests)\//.test(path)) {
    if (/projects|Lazygit/.test(path)) return "builds";
    if (/xp|Yazi/.test(path)) return "personnel";
    if (/Tracker|Radar|subjects/.test(path)) return "retina-v";
    if (/info/i.test(path)) return "profile";
  }
  return null;
}
