// Behavioral e2e suite for the Builds (lazygit) view, against the real
// (non-fixture) content build — PLAN.md Phase 5.
//
// Real content has exactly 3 projects, each with exactly 1 repo (transcript-tts,
// SafePass, daily-tech-digest — all github.com/ShevinuM/<name>, matching the
// git submodules under repos/). Commit snapshots and repo file indexes are
// generated by scripts/generate.mjs (`pnpm generate`, wired to `prebuild`)
// from the real submodule checkouts and the real GitHub API, so several
// assertions below are pinned to real, checked-in data (see the `head`/
// `node --experimental-strip-types` probes used while writing this file —
// re-verify these fixtures if `pnpm generate` is ever re-run against a
// different upstream state).
import { expect, test, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "../..");

async function gotoReady(page: Page, path: string) {
  await page.goto(path);
  await page.locator('[data-terminal-ready="true"]').waitFor({ state: "attached" });
}

/** Reads a real file's first line straight off disk (the git submodule
 * checkout under repos/), so the editor assertion below is checked against
 * ground truth, not a second copy of the same string. */
function firstLineOf(repoRelativePath: string): string {
  const content = readFileSync(join(ROOT, "repos", repoRelativePath), "utf8");
  return content.split("\n")[0];
}

const COMMIT_URL_RE = /^https:\/\/github\.com\/ShevinuM\/(transcript-tts|SafePass|daily-tech-digest)\/commit\/[0-9a-f]{8,}$/;

test.describe("Builds: project list + doc pane", () => {
  test.beforeEach(async ({ context }) => {
    // Default for every test in this file: no real network call to GitHub.
    // The two "commit refresh" tests below override this per-test with a
    // page-level route (which Playwright resolves before this context-level
    // one, since it's registered later) to actually exercise the mocked
    // fulfill/abort paths.
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("lists the 3 real projects, in frontmatter `order`", async ({ page }) => {
    await gotoReady(page, "/builds");
    const rows = page.locator('[data-testid="builds-file-row"]');
    await expect(rows).toHaveCount(3);
    const ids = await rows.evaluateAll((els) => els.map((el) => el.getAttribute("data-project-id")));
    expect(ids).toEqual(["transcript-tts", "SafePass", "daily-tech-digest"]);
    // Guards content.config.ts's `generateId` (case-preserving slug): Astro's
    // default glob() id generation lowercases entries, which would silently
    // rename this row "safepass.md".
    await expect(rows.nth(0)).toHaveText("M {} transcript-tts.md");
  });

  test("j/k (default panel [2] focus) moves project selection and changes the doc pane", async ({ page }) => {
    await gotoReady(page, "/builds");
    const doc = page.locator('[data-testid="builds-changes-body"]');
    await expect(doc).toContainText("transcript-tts");

    await page.keyboard.press("j");
    await expect(doc).toContainText("SafePass");
    await expect(page.locator('[data-testid="builds-file-row"][data-project-id="SafePass"]')).toHaveAttribute(
      "style",
      /rgba\(224, 69, 60, 0\.18\)/,
    );

    await page.keyboard.press("j");
    await expect(doc).toContainText("daily-tech-digest");

    await page.keyboard.press("k");
    await expect(doc).toContainText("SafePass");
  });

  // PLAN.md Phase 9 verify bullet (inherited from Phase 5's own verify):
  // "add the missing e2e focus-border assertions for Builds panels 0 and 1"
  // — panels 2/3/4's border-on-focus is already covered by other tests in
  // this file; 0 (Changes) and 1 (Status) never had their own, even though
  // panelBorder()/panelTitleColor() treat all five panels identically.
  test("0 focuses the Changes panel (border); 1 focuses the Status panel (border)", async ({ page }) => {
    await gotoReady(page, "/builds");
    const FOCUSED = /border: 1px solid rgb\(224, 69, 60\)/;
    const UNFOCUSED = /border: 1px solid rgba\(224, 69, 60, 0\.35\)/;

    await page.keyboard.press("0");
    await expect(page.locator('[data-testid="builds-panel-0"]')).toHaveAttribute("style", FOCUSED);
    await expect(page.locator('[data-testid="builds-panel-2"]')).toHaveAttribute("style", UNFOCUSED);

    await page.keyboard.press("1");
    await expect(page.locator('[data-testid="builds-panel-1"]')).toHaveAttribute("style", FOCUSED);
    await expect(page.locator('[data-testid="builds-panel-0"]')).toHaveAttribute("style", UNFOCUSED);
  });

  // PLAN.md Phase 9 "Vim extras" — gg/G in the Builds Files panel (project
  // list, panel [2]). The editor's own gg/G (repo-file scrolling) already
  // has a regression test further down this file; this is the project-list
  // analogue, "filtered list aware" doesn't apply here (no filter concept
  // in Builds), but must still respect the ~500ms double-tap window and do
  // nothing visible on a single "g".
  test("gg/G jump to the first/last project in panel [2]", async ({ page }) => {
    await gotoReady(page, "/builds");
    const doc = page.locator('[data-testid="builds-changes-body"]');
    await expect(doc).toContainText("transcript-tts");

    await page.keyboard.press("G");
    await expect(doc).toContainText("daily-tech-digest");
    await expect(page.locator('[data-testid="builds-file-row"][data-project-id="daily-tech-digest"]')).toHaveAttribute(
      "style",
      /rgba\(224, 69, 60, 0\.18\)/,
    );

    // A single "g" does nothing visible.
    await page.keyboard.press("g");
    await expect(doc).toContainText("daily-tech-digest");

    await page.keyboard.press("g");
    await expect(doc).toContainText("transcript-tts");
    await expect(page.locator('[data-testid="builds-file-row"][data-project-id="transcript-tts"]')).toHaveAttribute(
      "style",
      /rgba\(224, 69, 60, 0\.18\)/,
    );
  });
});

test.describe("Builds: commits panel", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("commit rows are real links matching github.com/ShevinuM/<repo>/commit/<sha>", async ({ page }) => {
    await gotoReady(page, "/builds");
    // Check all three projects' commit rows, not just the default active one.
    for (let i = 0; i < 3; i++) {
      const rows = page.locator('[data-testid="builds-commit-row"]');
      await expect(rows.first()).toBeVisible();
      const hrefs = await rows.evaluateAll((els) => els.map((el) => el.getAttribute("href")));
      expect(hrefs.length).toBeGreaterThan(0);
      for (const href of hrefs) {
        expect(href).toMatch(COMMIT_URL_RE);
      }
      if (i < 2) await page.keyboard.press("j"); // panel [2] still focused
    }
  });

  test("4 focuses the commits panel (border) and Enter opens the correct html_url in a new tab", async ({
    page,
    context,
  }) => {
    // Abort real navigation to github.com itself (separate host from
    // api.github.com) — we only care that the popup targets the right URL,
    // not that it actually loads. Capture the requested URL from the route
    // handler itself: once aborted, the popup's own `.url()` settles on
    // Chromium's internal "chrome-error://chromewebdata/" page, not the
    // originally requested address.
    let requestedUrl: string | null = null;
    await context.route("https://github.com/**", (route) => {
      requestedUrl = route.request().url();
      route.abort();
    });
    await gotoReady(page, "/builds");

    await page.keyboard.press("4");
    // The browser normalizes the authored inline `style` attribute (spaces
    // after colons/semicolons, rgb()/rgba() functional notation) — assert
    // against that normalized form, not the authored source string.
    await expect(page.locator('[data-testid="builds-panel-4"]')).toHaveAttribute(
      "style",
      /border: 1px solid rgb\(224, 69, 60\)/,
    );
    await expect(page.locator('[data-testid="builds-panel-2"]')).toHaveAttribute(
      "style",
      /border: 1px solid rgba\(224, 69, 60, 0\.35\)/,
    );

    const expectedHref = await page.locator('[data-testid="builds-commit-row"]').first().getAttribute("href");
    expect(expectedHref).toMatch(COMMIT_URL_RE);

    const popupPromise = context.waitForEvent("page");
    await page.keyboard.press("Enter");
    const popup = await popupPromise;
    await expect.poll(() => requestedUrl).toBe(expectedHref);
    await popup.close();
  });
});

test.describe("Builds: repo browsing (panel [3] -> pane [0])", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("3 focuses repos; Enter lists real submodule files (README.md present)", async ({ page }) => {
    await gotoReady(page, "/builds");
    await page.keyboard.press("3");
    await expect(page.locator('[data-testid="builds-panel-3"]')).toHaveAttribute(
      "style",
      /border: 1px solid rgb\(224, 69, 60\)/,
    );
    await page.keyboard.press("Enter");
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="README.md"]')).toBeVisible();
  });

  test("descend into a dir, open a file (real content, keyboard-driven); h walks back up; q exits the editor", async ({
    page,
  }) => {
    await gotoReady(page, "/builds");
    // Default active project is transcript-tts; switch to daily-tech-digest
    // (wraps k: (0-1+3)%3 = 2) so we have a repo with a genuine subdirectory
    // (transcript-tts is flat at its root).
    await page.keyboard.press("k");
    await expect(page.locator('[data-testid="builds-changes-body"]')).toContainText("daily-tech-digest");

    await page.keyboard.press("3");
    await page.keyboard.press("Enter"); // open daily-tech-digest's tree at root
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="feeds"]')).toBeVisible();

    // Root listing (repoTree.ts: dirs before files, case-insensitive name):
    // .github, feeds, newsletters, ... — one "j" reaches "feeds".
    await page.keyboard.press("j");
    await page.keyboard.press("Enter"); // descend into feeds/
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="dev_to.py"]')).toBeVisible();

    // Inside feeds/: up-entry(0), __init__.py(1), dev_to.py(2).
    await page.keyboard.press("j");
    await page.keyboard.press("j");
    await page.keyboard.press("Enter"); // open feeds/dev_to.py

    const scroller = page.locator('[data-testid="editor-scroller"]');
    await expect(scroller).toBeVisible();
    const firstLine = firstLineOf("daily-tech-digest/feeds/dev_to.py");
    await expect(scroller.locator('[data-line="1"] [data-testid="editor-line-text"]')).toHaveText(
      firstLine === "" ? " " : firstLine,
    );
    await expect(page.locator('[data-testid="editor-position"]')).toContainText("Top");

    await page.keyboard.press("q");
    await expect(scroller).toHaveCount(0);
    // Back in the repo tree at feeds/ (not the root, not the doc).
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="dev_to.py"]')).toBeVisible();

    await page.keyboard.press("h");
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="feeds"]')).toBeVisible();
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="dev_to.py"]')).toHaveCount(0);
  });

  test("editor Top/%/Bot position indicator updates on Ctrl-d (long file)", async ({ page }) => {
    await gotoReady(page, "/builds");
    await page.keyboard.press("k"); // daily-tech-digest
    await page.keyboard.press("3");
    await page.keyboard.press("Enter");
    // Click straight to tests/test_offline.py (1327 lines) — this test is
    // about editor scrolling, not tree-navigation key counting.
    await page.locator('[data-testid="builds-tree-row"][data-entry-name="tests"]').click();
    await page.locator('[data-testid="builds-tree-row"][data-entry-name="test_offline.py"]').click();

    const position = page.locator('[data-testid="editor-position"]');
    await expect(position).toContainText("Top");
    await expect(position).toContainText("1:1");

    await page.keyboard.press("Control+d");
    await expect(position).not.toContainText("Top 1:1");
    const afterOneScroll = await position.innerText();
    expect(afterOneScroll).not.toBe("Top 1:1");

    // Keep half-paging until "Bot" — bounded so a regression that makes
    // Ctrl-d a no-op fails instead of hanging.
    for (let i = 0; i < 200; i++) {
      const text = await position.innerText();
      if (text.includes("Bot")) break;
      await page.keyboard.press("Control+d");
    }
    await expect(position).toContainText("Bot");

    // Ctrl-u moves back up a half page (away from Bot).
    await page.keyboard.press("Control+u");
    await expect(position).not.toContainText("Bot");

    // gg / G jump straight to the top/bottom (PLAN.md Phase 5 scope item 3).
    await page.keyboard.press("g");
    await page.keyboard.press("g");
    await expect(position).toContainText("Top 1:1");

    await page.keyboard.press("G");
    await expect(position).toContainText("Bot");
    await expect(position).toContainText("1327:1");
  });
});

test.describe("Builds: t -> tracker", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("t from builds enters the tracker (Retina-V) view", async ({ page }) => {
    await gotoReady(page, "/builds");
    await page.keyboard.press("t");
    await expect(page).toHaveURL(/\/retina-v$/);
  });
});

test.describe("Builds: client-side commit refresh", () => {
  test("route-fulfill with a fake commit replaces the snapshot list", async ({ page }) => {
    const fakeCommit = {
      sha: "deadbeef00001111222233334444555566667777",
      commit: { message: "fake live commit for e2e\n\nbody text", author: { name: "Test Bot" } },
      author: { login: "TestBot" },
      html_url: "https://github.com/ShevinuM/transcript-tts/commit/deadbeef00001111222233334444555566667777",
    };
    // Playwright resolves the most-recently-registered matching route
    // first, so the broad "every repo" abort must be registered BEFORE the
    // specific transcript-tts fulfill — otherwise the abort (registered
    // second) would shadow it entirely.
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/transcript-tts/commits**", (route) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify([fakeCommit]) }),
    );

    await gotoReady(page, "/builds");
    await expect
      .poll(async () => page.locator('[data-testid="builds-commit-row"]').first().getAttribute("href"), {
        timeout: 5000,
      })
      .toBe(fakeCommit.html_url);
  });

  test("route-abort keeps the committed snapshot list intact", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/builds");
    // Give the aborted fetch a moment to settle before asserting nothing changed.
    await page.waitForTimeout(500);
    await expect(page.locator('[data-testid="builds-commit-row"]').first()).toHaveAttribute(
      "href",
      "https://github.com/ShevinuM/transcript-tts/commit/ab88cac7eb2fba7cccc6915055a5983c4a6b77f4",
    );
  });

  // PLAN.md Phase 5 verify bullet: "API 403 -> snapshot list unchanged" — a
  // distinct code path from the network-level abort above (fetchLiveCommits'
  // `!res.ok` branch vs its catch block), so it gets its own test.
  test("API 403 keeps the committed snapshot list intact", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) =>
      route.fulfill({
        status: 403,
        contentType: "application/json",
        body: JSON.stringify({ message: "API rate limit exceeded" }),
      }),
    );
    await gotoReady(page, "/builds");
    await page.waitForTimeout(500);
    await expect(page.locator('[data-testid="builds-commit-row"]').first()).toHaveAttribute(
      "href",
      "https://github.com/ShevinuM/transcript-tts/commit/ab88cac7eb2fba7cccc6915055a5983c4a6b77f4",
    );
  });
});
