// Behavioral e2e suite for the Builds (lazygit) view, against the real
// (non-fixture) content build — PLAN.md Phase 4 ("Builds rework").
//
// Real content has exactly 3 projects, each with exactly 1 repo
// (transcript-tts, SafePass, daily-tech-digest — all github.com/ShevinuM/<name>,
// matching the git submodules under repos/), so panel [3]'s flat repo list
// is those 3 rows plus the virtual "all-projects" entry, in that order.
// Commit snapshots and repo file indexes are generated by scripts/generate.mjs
// (`pnpm generate`, wired to prebuild) from the real submodule checkouts and
// the real GitHub API — several assertions below are pinned to that
// checked-in data; re-verify them if `pnpm generate` is ever re-run against
// a different upstream state.
import { expect, test, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "../..");

async function gotoReady(page: Page, path: string) {
  await page.goto(path);
  await page.locator('[data-terminal-ready="true"]').waitFor({ state: "attached" });
}

/** Reads a real file straight off disk (the git submodule checkout under
 * repos/), so assertions below are checked against ground truth, not a
 * second copy of the same string. */
function fileLines(repoRelativePath: string): string[] {
  return readFileSync(join(ROOT, "repos", repoRelativePath), "utf8").split("\n");
}

const COMMIT_URL_RE = /^https:\/\/github\.com\/ShevinuM\/(transcript-tts|SafePass|daily-tech-digest)\/commit\/[0-9a-f]{7,40}$/;

/** Opens a repo's working tree into panel [2] via panel [3] (click), from a
 * freshly-loaded page, and waits for the tree to actually render — the
 * working-tree index is fetched asynchronously (`/generated/repos/<repo>.json`),
 * so a bare click leaves a brief window where panel [2] still looks empty;
 * every test that needs to browse a tree starts here rather than racing that
 * fetch itself. */
async function openRepoTree(page: Page, repoName: string) {
  await page.locator(`[data-testid="builds-repo-row"][data-repo-name="${repoName}"]`).click();
  await expect(page.locator('[data-testid="builds-tree-row"]').first()).toBeVisible();
}

test.describe("Builds: panel [3] flat repo list + all-projects", () => {
  test.beforeEach(async ({ context }) => {
    // Default for every test in this file: no real network call to GitHub.
    // Tests that specifically exercise the mocked fulfill/abort paths
    // override this per-test/per-page (Playwright resolves the
    // most-recently-registered matching route first).
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("lists the 3 real repos (frontmatter order) plus all-projects", async ({ page }) => {
    await gotoReady(page, "/builds");
    const rows = page.locator('[data-testid="builds-repo-row"]');
    await expect(rows).toHaveCount(4);
    const names = await rows.evaluateAll((els) => els.map((el) => el.getAttribute("data-repo-name")));
    expect(names).toEqual(["transcript-tts", "SafePass", "daily-tech-digest", "all-projects"]);
    const allProjectsRow = rows.last();
    await expect(allProjectsRow).toHaveAttribute("data-all-projects", "true");
    for (const row of [rows.nth(0), rows.nth(1), rows.nth(2)]) {
      await expect(row).toHaveAttribute("data-all-projects", "false");
    }
  });

  test("panel [2] is empty until a repo is opened; clicking a repo loads its tree", async ({ page }) => {
    await gotoReady(page, "/builds");
    await expect(page.locator('[data-testid="builds-tree-row"]')).toHaveCount(0);

    await openRepoTree(page, "transcript-tts");
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="README.md"]')).toBeVisible();
  });

  test("Enter on the highlighted repo row also loads its tree (keyboard path)", async ({ page }) => {
    await gotoReady(page, "/builds");
    await page.keyboard.press("3"); // focus panel [3]
    await expect(page.locator('[data-testid="builds-panel-3"]')).toHaveAttribute(
      "style",
      /border: 1px solid rgb\(224, 69, 60\)/,
    );
    await page.keyboard.press("Enter"); // default highlight = transcript-tts (idx 0)
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="README.md"]')).toBeVisible();
  });

  test("all-projects lists the 3 real project .md files", async ({ page }) => {
    await gotoReady(page, "/builds");
    await openRepoTree(page, "all-projects");
    const rows = page.locator('[data-testid="builds-tree-row"]');
    const names = await rows.evaluateAll((els) => els.map((el) => el.getAttribute("data-entry-name")));
    expect(names.sort()).toEqual(["SafePass.md", "daily-tech-digest.md", "transcript-tts.md"].sort());
  });

  test("all-projects: commits panel shows the data-driven local-only line, not commit rows", async ({ page }) => {
    await gotoReady(page, "/builds");
    await page.keyboard.press("3");
    await page.keyboard.press("j");
    await page.keyboard.press("j");
    await page.keyboard.press("j"); // wrap to all-projects (idx 3)
    await expect(page.locator('[data-testid="builds-repo-row"][data-all-projects="true"]')).toHaveAttribute(
      "style",
      /rgba\(224, 69, 60, 0\.22\)/,
    );
    await expect(page.locator('[data-testid="builds-commit-row"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="builds-panel-4"]')).toContainText("local only");
  });
});

test.describe("Builds: panel [2] tree browsing + panel [0] preview", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("clicking a file previews its content in panel [0] without opening the editor", async ({ page }) => {
    await gotoReady(page, "/builds");
    await openRepoTree(page, "transcript-tts");
    await page.locator('[data-testid="builds-tree-row"][data-entry-name="server.py"]').click();

    const expectedLines = fileLines("transcript-tts/server.py");
    await expect(page.locator('[data-testid="builds-preview-line"]').first()).toContainText(expectedLines[0]);
    // Click previews only — the full-screen editor must not open.
    await expect(page.locator('[data-testid="editor-scroller"]')).toHaveCount(0);
  });

  test("Enter on a file opens the full-screen vim editor; :q returns to the tree", async ({ page }) => {
    await gotoReady(page, "/builds");
    await openRepoTree(page, "transcript-tts");
    // Click-select README.md (previews only), then focus panel [2] and press
    // Enter to open it in the editor — exercising the click-selects/
    // Enter-opens split (PLAN.md Phase 4 item 3).
    await page.locator('[data-testid="builds-tree-row"][data-entry-name="README.md"]').click();
    await page.keyboard.press("2");
    await page.keyboard.press("Enter");

    const scroller = page.locator('[data-testid="editor-scroller"]');
    await expect(scroller).toBeVisible();
    const expectedFirstLine = fileLines("transcript-tts/README.md")[0];
    await expect(scroller.locator('[data-line="1"] [data-testid="editor-line-text"]')).toHaveText(expectedFirstLine);

    await page.keyboard.press(":");
    await page.keyboard.type("q");
    await page.keyboard.press("Enter");
    await expect(scroller).toHaveCount(0);
    await expect(page.locator('[data-testid="builds-tree-row"]').first()).toBeVisible();
  });

  test("descend into a dir (click), open a file, h walks back up", async ({ page }) => {
    await gotoReady(page, "/builds");
    await openRepoTree(page, "daily-tech-digest");
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="feeds"]')).toBeVisible();

    await page.locator('[data-testid="builds-tree-row"][data-entry-name="feeds"]').click();
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="dev_to.py"]')).toBeVisible();

    await page.locator('[data-testid="builds-tree-row"][data-entry-name="dev_to.py"]').click();
    const expectedLines = fileLines("daily-tech-digest/feeds/dev_to.py");
    await expect(page.locator('[data-testid="builds-preview-line"]').first()).toContainText(expectedLines[0]);

    // Files panel [2] title reflects the open repo (no commit suffix — this
    // is the working tree).
    await expect(page.locator('[data-testid="builds-panel-2"]')).toContainText("daily-tech-digest");
    await expect(page.locator('[data-testid="builds-panel-2"]')).not.toContainText("@");

    await page.keyboard.press("2");
    await page.keyboard.press("h");
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="feeds"]')).toBeVisible();
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="dev_to.py"]')).toHaveCount(0);
  });

  test("gg/G jump to the first/last row of the open tree", async ({ page }) => {
    await gotoReady(page, "/builds");
    await openRepoTree(page, "daily-tech-digest");
    await page.keyboard.press("2");

    await page.keyboard.press("G");
    const lastRow = page.locator('[data-testid="builds-tree-row"]').last();
    await expect(lastRow).toHaveAttribute("style", /rgba\(224, 69, 60, 0\.18\)/);

    // A single "g" does nothing visible.
    await page.keyboard.press("g");
    await expect(lastRow).toHaveAttribute("style", /rgba\(224, 69, 60, 0\.18\)/);

    await page.keyboard.press("g");
    const firstRow = page.locator('[data-testid="builds-tree-row"]').first();
    await expect(firstRow).toHaveAttribute("style", /rgba\(224, 69, 60, 0\.18\)/);
  });

  test("editor Top/%/Bot position indicator updates on Ctrl-d (long file)", async ({ page }) => {
    await gotoReady(page, "/builds");
    await openRepoTree(page, "daily-tech-digest");
    await page.locator('[data-testid="builds-tree-row"][data-entry-name="tests"]').click();
    await page.locator('[data-testid="builds-tree-row"][data-entry-name="test_offline.py"]').click();
    await page.keyboard.press("2");
    await page.keyboard.press("Enter"); // open the previewed file in the editor

    const position = page.locator('[data-testid="editor-position"]');
    await expect(position).toContainText("Top");
    await expect(position).toContainText("1:1");

    const totalLines = fileLines("daily-tech-digest/tests/test_offline.py").length;

    await page.keyboard.press("Control+d");
    await expect(position).not.toContainText("Top 1:1");

    for (let i = 0; i < 200; i++) {
      const text = await position.innerText();
      if (text.includes("Bot")) break;
      await page.keyboard.press("Control+d");
    }
    await expect(position).toContainText("Bot");

    await page.keyboard.press("G");
    await expect(position).toContainText("Bot");
    await expect(position).toContainText(`${totalLines}:1`);
  });
});

test.describe("Builds: panel [4] commits track ONLY panel [3] (bug fix)", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("commits stay fixed while navigating panel [2]/[0]; change only on panel [3] selection", async ({ page }) => {
    await gotoReady(page, "/builds");
    const shaOf = () => page.locator('[data-testid="builds-commit-row"]').first().getAttribute("data-sha8");

    // Selecting + opening daily-tech-digest via panel [3] IS a legitimate
    // panel [3] selection change, so commits update to match it once.
    await openRepoTree(page, "daily-tech-digest");
    const afterSelect = await shaOf();
    expect(afterSelect).toBeTruthy();

    // Browsing WITHIN that same repo's tree/preview — panel [2]/[0] — must
    // not move panel [4] again (2026-08-17 bug report: "commits change
    // dynamically when I move across files").
    await page.locator('[data-testid="builds-tree-row"][data-entry-name="feeds"]').click();
    await expect(shaOf()).resolves.toBe(afterSelect);
    await page.locator('[data-testid="builds-tree-row"][data-entry-name="dev_to.py"]').click();
    await expect(shaOf()).resolves.toBe(afterSelect);
    await page.keyboard.press("0"); // focus the preview panel too
    await expect(shaOf()).resolves.toBe(afterSelect);

    // Only moving the panel [3] selection changes commits again.
    await page.keyboard.press("3");
    await page.keyboard.press("k"); // daily-tech-digest (idx 2) -> SafePass (idx 1)
    await expect.poll(shaOf).not.toBe(afterSelect);
  });
});

test.describe("Builds: commit click loads a tree (no popup); 'o' opens GitHub", () => {
  test("clicking a commit fetches its tree into panel [2] — no new tab", async ({ page, context }) => {
    const fakeTree = { sha: "deadbeef", tree: [{ path: "README.md", type: "blob" }], truncated: false };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/transcript-tts/git/trees/**", (route) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(fakeTree) }),
    );
    await gotoReady(page, "/builds");

    let popupSeen = false;
    context.on("page", () => (popupSeen = true));

    await page.locator('[data-testid="builds-commit-row"]').first().click();
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="README.md"]')).toBeVisible();
    await expect(page.locator('[data-testid="builds-panel-2"]')).toContainText("@ab88cac7");
    expect(popupSeen).toBe(false);
    expect(context.pages().length).toBe(1);
  });

  test("'o' on the selected commit opens its html_url on GitHub in a new tab", async ({ page, context }) => {
    let requestedUrl: string | null = null;
    await context.route("https://github.com/**", (route) => {
      requestedUrl = route.request().url();
      route.abort();
    });
    await context.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/builds");

    await page.keyboard.press("4");
    await expect(page.locator('[data-testid="builds-panel-4"]')).toHaveAttribute(
      "style",
      /border: 1px solid rgb\(224, 69, 60\)/,
    );
    const expectedHref = await page.locator('[data-testid="builds-commit-row"]').first().getAttribute("data-html-url");
    expect(expectedHref).toMatch(COMMIT_URL_RE);

    const popupPromise = context.waitForEvent("page");
    await page.keyboard.press("o");
    const popup = await popupPromise;
    await expect.poll(() => requestedUrl).toBe(expectedHref);
    await popup.close();
  });

  test("all-projects: 'o' and Enter on the commits panel are no-ops (commit-browsing disabled)", async ({
    page,
    context,
  }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/builds");
    await page.keyboard.press("3");
    await page.keyboard.press("j");
    await page.keyboard.press("j");
    await page.keyboard.press("j"); // all-projects
    await page.keyboard.press("4");

    let popupSeen = false;
    context.on("page", () => (popupSeen = true));
    await page.keyboard.press("o");
    await page.keyboard.press("Enter");
    await page.waitForTimeout(300);
    expect(popupSeen).toBe(false);
    expect(context.pages().length).toBe(1);
  });
});

test.describe("Builds: commit-tree / file-content fetch failures preserve state", () => {
  test("commit-tree fetch failure shows a transient error and keeps the previously open tree", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/builds");
    await openRepoTree(page, "transcript-tts");
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="README.md"]')).toBeVisible();

    // The default commits-panel abort route (registered above) also covers
    // the trees endpoint, so this commit click is guaranteed to fail.
    await page.locator('[data-testid="builds-commit-row"]').first().click();

    await expect(page.locator('[data-testid="builds-commit-error"]')).toBeVisible();
    // Working tree from before the failed click is still exactly what's shown.
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="README.md"]')).toBeVisible();
    await expect(page.locator('[data-testid="builds-panel-2"]')).not.toContainText("@");
  });

  test("commit-tree fetch 403 (rate limit) behaves the same as a network abort", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) =>
      route.fulfill({ status: 403, contentType: "application/json", body: JSON.stringify({ message: "rate limited" }) }),
    );
    await gotoReady(page, "/builds");
    await page.locator('[data-testid="builds-commit-row"]').first().click();
    await expect(page.locator('[data-testid="builds-commit-error"]')).toBeVisible();
  });

  test("file-content fetch failure inside a commit tree shows an error line, keeps the tree", async ({ page }) => {
    const fakeTree = { sha: "deadbeef", tree: [{ path: "README.md", type: "blob" }], truncated: false };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/transcript-tts/git/trees/**", (route) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(fakeTree) }),
    );
    // contents/** is still covered by the broad abort above.
    await gotoReady(page, "/builds");
    await page.locator('[data-testid="builds-commit-row"]').first().click();
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="README.md"]')).toBeVisible();

    await page.locator('[data-testid="builds-tree-row"][data-entry-name="README.md"]').click();
    await expect(page.locator('[data-testid="builds-changes-body"]')).toContainText("Failed to load that file.");
    // The tree itself is untouched by the preview failure.
    await expect(page.locator('[data-testid="builds-tree-row"][data-entry-name="README.md"]')).toBeVisible();
  });

  test("binary/oversize file at a commit shows the binary message, not garbled content", async ({ page }) => {
    const fakeTree = { sha: "deadbeef", tree: [{ path: "asset.bin", type: "blob" }], truncated: false };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/transcript-tts/git/trees/**", (route) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(fakeTree) }),
    );
    await page.route("**/api.github.com/repos/ShevinuM/transcript-tts/contents/**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ size: 999_999, encoding: "base64", content: "" }),
      }),
    );
    await gotoReady(page, "/builds");
    await page.locator('[data-testid="builds-commit-row"]').first().click();
    await page.locator('[data-testid="builds-tree-row"][data-entry-name="asset.bin"]').click();
    await expect(page.locator('[data-testid="builds-changes-body"]')).toContainText("Binary or too large to preview.");
  });
});

test.describe("Builds: panel [3] spinner while a fetch is in flight", () => {
  test("spinner appears on the repo row during a delayed fetch and disappears after", async ({ page }) => {
    const fakeCommit = {
      sha: "deadbeef00001111222233334444555566667777",
      commit: { message: "fake live commit for e2e", author: { name: "Test Bot" } },
      author: { login: "TestBot" },
      html_url: "https://github.com/ShevinuM/transcript-tts/commit/deadbeef00001111222233334444555566667777",
    };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/transcript-tts/commits**", async (route) => {
      await new Promise((r) => setTimeout(r, 500));
      await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify([fakeCommit]) });
    });

    await gotoReady(page, "/builds");
    const spinner = page.locator('[data-testid="builds-repo-spinner"]');
    await expect(spinner).toBeVisible();
    await expect(spinner).toHaveCount(0, { timeout: 5000 });
  });
});

test.describe("Builds: commit row heights render at full glyph height (PLAN.md 4.6)", () => {
  test("15 live-mocked commits render unclipped rows at 1512x945", async ({ page }) => {
    await page.setViewportSize({ width: 1512, height: 945 });
    const fakeCommits = Array.from({ length: 15 }, (_, i) => ({
      sha: `${i.toString(16).padStart(2, "0")}${"deadbeefcafefeed1234567890abcdef123456".slice(2)}`,
      commit: { message: `fake commit number ${i} with a reasonably long message`, author: { name: "Test Bot" } },
      author: { login: "TestBot" },
      html_url: `https://github.com/ShevinuM/transcript-tts/commit/fake${i}`,
    }));
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/transcript-tts/commits**", (route) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(fakeCommits) }),
    );

    await gotoReady(page, "/builds");
    const rows = page.locator('[data-testid="builds-commit-row"]');
    await expect(rows).toHaveCount(15);

    const measurements = await rows.evaluateAll((els) =>
      els.map((el) => {
        const rect = el.getBoundingClientRect();
        const lineHeight = parseFloat(getComputedStyle(el).lineHeight);
        return { height: rect.height, lineHeight };
      }),
    );
    for (const { height, lineHeight } of measurements) {
      // A clipped/overlapping row (the reported bug) renders shorter than
      // its own computed line-height; a full-height row never does.
      expect(height).toBeGreaterThanOrEqual(lineHeight - 0.5);
    }
  });
});

test.describe("Builds: t -> tracker", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("t from builds enters the tracker (Retina-V) view", async ({ page }) => {
    await gotoReady(page, "/builds");
    await page.keyboard.press("t");
    await expect(page).toHaveURL(/\/retina-v$/);
  });
});

test.describe("Builds: panel focus border (panels 0 and 1)", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("0 focuses the Changes panel (border); 1 focuses the Status panel (border)", async ({ page }) => {
    await gotoReady(page, "/builds");
    const FOCUSED = /border: 1px solid rgb\(224, 69, 60\)/;
    const UNFOCUSED = /border: 1px solid rgba\(224, 69, 60, 0\.35\)/;

    await page.keyboard.press("0");
    await expect(page.locator('[data-testid="builds-panel-0"]')).toHaveAttribute("style", FOCUSED);
    await expect(page.locator('[data-testid="builds-panel-2"]')).toHaveAttribute("style", UNFOCUSED);

    await page.keyboard.press("1");
    await expect(page.locator('[data-testid="builds-panel-1"]')).toHaveAttribute("style", FOCUSED);
    await expect(page.locator('[data-testid="builds-panel-0"]')).toHaveAttribute("style", UNFOCUSED);
  });
});

test.describe("Builds: client-side commit refresh (panel [3] selection only)", () => {
  test("route-fulfill with a fake commit replaces the snapshot list for the selected repo", async ({ page }) => {
    const fakeCommit = {
      sha: "deadbeef00001111222233334444555566667777",
      commit: { message: "fake live commit for e2e\n\nbody text", author: { name: "Test Bot" } },
      author: { login: "TestBot" },
      html_url: "https://github.com/ShevinuM/transcript-tts/commit/deadbeef00001111222233334444555566667777",
    };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/transcript-tts/commits**", (route) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify([fakeCommit]) }),
    );

    await gotoReady(page, "/builds");
    await expect
      .poll(async () => page.locator('[data-testid="builds-commit-row"]').first().getAttribute("data-sha8"), {
        timeout: 5000,
      })
      .toBe("deadbeef");
  });

  test("route-abort keeps the committed snapshot list intact", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/builds");
    await page.waitForTimeout(500);
    await expect(page.locator('[data-testid="builds-commit-row"]').first()).toHaveAttribute("data-sha8", "ab88cac7");
  });

  test("API 403 keeps the committed snapshot list intact", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) =>
      route.fulfill({ status: 403, contentType: "application/json", body: JSON.stringify({ message: "API rate limit exceeded" }) }),
    );
    await gotoReady(page, "/builds");
    await page.waitForTimeout(500);
    await expect(page.locator('[data-testid="builds-commit-row"]').first()).toHaveAttribute("data-sha8", "ab88cac7");
  });
});
