// Behavioral e2e suite for the Repositories (lazygit) view, against the real
// (non-fixture) content build — exactly 8 real repos, SafePass removed.
//
// Real content has exactly 8 projects, each with exactly 1 repo, in this
// frontmatter `order` (daily-tech-digest, transcript-tts,
// Legend-of-Arlo-Guardians-Gauntlet, SpotifyPal, Advent-of-Code-2024,
// Advent-Of-Code-2023, Sheldon, Data-Structures-And-Algorithms — all
// github.com/ShevinuM/<name>, matching the git submodules under repos/), so
// panel [3]'s flat repo list is those 8 rows PLUS the virtual "all-projects"
// entry, pinned to the FRONT of that list, and it's the default selection on
// load: `selectedRepoIdx = $state(0)` points at it, and a mount effect
// in Repositories.svelte loads its tree into panel [2] immediately, no click or
// keypress required. daily-tech-digest is therefore idx 1 (not idx 0) — any
// test that needs a live commits fetch running on mount and a populated
// commits panel to click into must explicitly select daily-tech-digest
// first; nothing here hardcodes the default-selection assumption without
// doing that.
//
// Panel [2]'s Files pane is a lazygit-style tree: the FULL nested tree
// renders at once, every dir starts expanded, and click/Enter on a dir
// toggles collapse in place — there is no `../` row anywhere, and
// clicking/entering a dir NEVER changes what repo is selected or what
// panel [4] shows.
//
// Commit snapshots and repo file indexes are generated by scripts/generate.mjs
// (`pnpm generate`, wired to prebuild) from the real submodule checkouts and
// the real GitHub API — a snapshot's own commit shas are LIVE-REFRESHABLE
// data (a new real commit lands upstream, `pnpm generate` picks it up), so
// nothing below hardcodes one: `loadCommitSnapshot()`/`dailyTechDigestHead`
// parse the checked-in JSON at test time, same "derive the expectation from
// the real source" convention nav.spec.ts's toast-dismissal suite uses. The
// repo COUNT/order/names above are structural, not live-refreshable, and
// stay asserted directly.
import { expect, test, type Page } from "./fixtures.ts";
// This spec's `context` fixture (imported
// from ./fixtures.ts, not raw "@playwright/test") pre-seeds the boot-seen
// sessionStorage flag before every navigation, so BootSequence.svelte's
// ~4.6s unskippable sequence never runs for these tests — see that
// file's header comment for why this is a context-fixture override
// rather than a per-goto-helper change.
import { readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "../..");

async function gotoReady(page: Page, path: string) {
  await page.goto(path);
  await page.locator('[data-terminal-ready="true"]').waitFor({ state: "attached" });
}

/** Reads a real file straight off disk (the git submodule checkout under
 * repos/), so assertions below are checked against ground truth, not a
 * second copy of the same string. */
function fileLines(repoRelativePath: string): string[] {
  return readFileSync(join(ROOT, "repos", repoRelativePath), "utf8").split("\n");
}

interface CommitSnapshotEntry {
  sha: string;
  sha8: string;
  msg: string;
  html_url: string;
  initials: string;
}

/** `src/generated/commits/<repo>.json` — the COMMITTED snapshot Repositories.svelte
 * falls back to whenever a live GitHub commits fetch is aborted/403s (this
 * file's own header comment). Parsed at test time rather than a hardcoded
 * sha8 literal, so a `pnpm generate` refresh (a new real commit landing
 * upstream) can never silently break these assertions — same "derive the
 * expectation from the real source" convention nav.spec.ts's toast-dismissal
 * suite already uses for the seeded notification pool. */
function loadCommitSnapshot(repo: string): CommitSnapshotEntry[] {
  return JSON.parse(readFileSync(join(ROOT, "src/generated/commits", `${repo}.json`), "utf8")) as CommitSnapshotEntry[];
}

/** The head (most recent) commit of daily-tech-digest's own committed
 * snapshot — every "keeps the committed snapshot intact" assertion below
 * checks against this, live-refreshable and never hardcoded. daily-tech-
 * digest is no longer the default-selected repo (see header comment), so
 * every test using this now explicitly selects it first via
 * `selectRepoRow`/`openRepoTree`. */
const dailyTechDigestHead = loadCommitSnapshot("daily-tech-digest")[0];

const COMMIT_URL_RE =
  /^https:\/\/github\.com\/ShevinuM\/(daily-tech-digest|transcript-tts|Legend-of-Arlo-Guardians-Gauntlet|SpotifyPal|Advent-of-Code-2024|Advent-Of-Code-2023|Sheldon|Data-Structures-And-Algorithms)\/commit\/[0-9a-f]{7,40}$/;

/** Clicks a panel [3] repo row — this both selects it (panel [4]'s commits
 * now track it) AND loads its working tree into panel [2] (no separate
 * select-then-open step). Waits for the tree to actually render — the working-tree index is fetched
 * asynchronously (`/generated/repos/<repo>.json`), so a bare click leaves a
 * brief window where panel [2] still looks empty/stale; every test that
 * needs a specific repo's tree or commits starts here rather than racing
 * that fetch itself. */
async function openRepoTree(page: Page, repoName: string) {
  await page.locator(`[data-testid="repositories-repo-row"][data-repo-name="${repoName}"]`).click();
  await expect(page.locator('[data-testid="repositories-tree-row"]').first()).toBeVisible();
}

/** Matches tree rows by name; pass `depth` to disambiguate when the same
 * filename appears more than once in a tree at different nesting levels
 * (daily-tech-digest genuinely has this — both `README.md` at the repo root
 * AND `site/README.md`, now simultaneously visible since the whole tree
 * renders at once). */
function treeRow(page: Page, name: string, depth?: number) {
  const depthSelector = depth === undefined ? "" : `[data-depth="${depth}"]`;
  return page.locator(`[data-testid="repositories-tree-row"][data-entry-name="${name}"]${depthSelector}`);
}

/** Clicking a row leaves real DOM focus on it (it's a `role="button"`
 * div with its own `onkeydown` for Enter/Space, mirroring native button
 * semantics — Repositories.svelte's own pattern for repo rows AND tree rows).
 * A later keyboard-driven selection change (ArrowUp/ArrowDown) updates
 * Svelte state but does NOT move DOM focus off that row, so pressing Enter
 * afterward would hit that row's own stale-closure handler FIRST (before
 * Terminal's global keydown listener sees it), reactivating whatever was
 * clicked rather than whatever the arrow keys most recently selected.
 * Blurring first makes a subsequent Enter reach only the global handler,
 * driven by the true current selection — this is a test-only workaround for
 * that DOM-focus quirk, not a product fix. */
async function blurActive(page: Page) {
  await page.evaluate(() => (document.activeElement as HTMLElement | null)?.blur());
}

test.describe("Repositories: panel [3] repo list — all-projects pinned first + default-selected", () => {
  test.beforeEach(async ({ context }) => {
    // Default for every test in this file: no real network call to GitHub.
    // Tests that specifically exercise the mocked fulfill/abort paths
    // override this per-test/per-page (Playwright resolves the
    // most-recently-registered matching route first).
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("all-projects is row 0; the 8 real repos follow in frontmatter order (Item 5)", async ({ page }) => {
    await gotoReady(page, "/repositories");
    const rows = page.locator('[data-testid="repositories-repo-row"]');
    await expect(rows).toHaveCount(9);
    const names = await rows.evaluateAll((els) => els.map((el) => el.getAttribute("data-repo-name")));
    expect(names).toEqual([
      "all-projects",
      "daily-tech-digest",
      "transcript-tts",
      "Legend-of-Arlo-Guardians-Gauntlet",
      "SpotifyPal",
      "Advent-of-Code-2024",
      "Advent-Of-Code-2023",
      "Sheldon",
      "Data-Structures-And-Algorithms",
    ]);
    await expect(rows.first()).toHaveAttribute("data-all-projects", "true");
    for (let i = 1; i < 9; i++) {
      await expect(rows.nth(i)).toHaveAttribute("data-all-projects", "false");
    }
  });

  test("Files pane shows the all-projects tree on mount — no click or keypress needed (Item 5)", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await expect(page.locator('[data-testid="repositories-tree-row"]').first()).toBeVisible();
    await expect(page.locator('[data-testid="repositories-panel-2"]')).toContainText("all-projects");

    const names = await page
      .locator('[data-testid="repositories-tree-row"]')
      .evaluateAll((els) => els.map((el) => el.getAttribute("data-entry-name")));
    expect(names.sort()).toEqual(
      [
        "daily-tech-digest.md",
        "transcript-tts.md",
        "Legend-of-Arlo-Guardians-Gauntlet.md",
        "SpotifyPal.md",
        "Advent-of-Code-2024.md",
        "Advent-Of-Code-2023.md",
        "Sheldon.md",
        "Data-Structures-And-Algorithms.md",
      ].sort(),
    );

    // "Loaded" isn't the same claim as "selected" (Item 5 requires both) —
    // focus panel [3] with zero j/k presses and confirm row 0 (all-projects)
    // already carries the highlighted-selection background.
    await page.keyboard.press("3");
    await expect(page.locator('[data-testid="repositories-repo-row"]').first()).toHaveAttribute(
      "style",
      /rgba\(224, 69, 60, 0\.22\)/,
    );
  });

  test("clicking a different repo row swaps panel [2] over to that repo's tree", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await expect(page.locator('[data-testid="repositories-panel-2"]')).toContainText("all-projects");

    await openRepoTree(page, "transcript-tts");
    await expect(treeRow(page, "README.md")).toBeVisible();
    await expect(page.locator('[data-testid="repositories-panel-2"]')).toContainText("transcript-tts");
    await expect(page.locator('[data-testid="repositories-panel-2"]')).not.toContainText("all-projects");
  });

  test("Enter on the highlighted repo row also loads its tree (keyboard path)", async ({ page }) => {
    await gotoReady(page, "/repositories");
    // Move off the mount-time default (all-projects) first so pressing
    // Enter below is actually exercising the keyboard path, not just
    // observing what was already loaded on mount.
    await openRepoTree(page, "transcript-tts");
    await expect(treeRow(page, "README.md")).toBeVisible();

    await blurActive(page); // see helper doc — avoids a stale-focus double-fire on Enter below
    await page.keyboard.press("3"); // focus panel [3]
    await expect(page.locator('[data-testid="repositories-panel-3"]')).toHaveAttribute(
      "style",
      /border: 1px solid rgb\(224, 69, 60\)/,
    );
    await page.keyboard.press("ArrowUp"); // wrap from transcript-tts (idx 2) back to all-projects (idx 0)
    await page.keyboard.press("ArrowUp");
    await page.keyboard.press("Enter");
    await expect(treeRow(page, "daily-tech-digest.md")).toBeVisible();
    await expect(treeRow(page, "README.md")).toHaveCount(0);
  });

  test("all-projects lists all 8 real project .md files", async ({ page }) => {
    await gotoReady(page, "/repositories");
    const rows = page.locator('[data-testid="repositories-tree-row"]');
    const names = await rows.evaluateAll((els) => els.map((el) => el.getAttribute("data-entry-name")));
    expect(names.sort()).toEqual(
      [
        "daily-tech-digest.md",
        "transcript-tts.md",
        "Legend-of-Arlo-Guardians-Gauntlet.md",
        "SpotifyPal.md",
        "Advent-of-Code-2024.md",
        "Advent-Of-Code-2023.md",
        "Sheldon.md",
        "Data-Structures-And-Algorithms.md",
      ].sort(),
    );
    // all-projects is a flat doc bundle — no directories in its tree.
    await expect(page.locator('[data-testid="repositories-tree-row"][data-entry-type="dir"]')).toHaveCount(0);
  });

  test("all-projects: commits panel shows the data-driven local-only line, not commit rows", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await page.keyboard.press("3");
    await page.locator('[data-testid="repositories-repo-row"][data-repo-name="all-projects"]').click();
    await expect(page.locator('[data-testid="repositories-repo-row"][data-all-projects="true"]')).toHaveAttribute(
      "style",
      /rgba\(224, 69, 60, 0\.22\)/,
    );
    await expect(page.locator('[data-testid="repositories-commit-row"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="repositories-panel-4"]')).toContainText("local only");
  });
});

test.describe("Repositories: panel [2] lazygit-style tree — expand/collapse, no ../ row (Item 4)", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("a known subdir's children render immediately on load — no click needed to descend", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");

    // "feeds" is a real subdirectory of daily-tech-digest with several
    // files in it; all of them must already be visible without ever
    // clicking "feeds" itself.
    const feedsDir = treeRow(page, "feeds");
    await expect(feedsDir).toBeVisible();
    await expect(feedsDir).toHaveAttribute("data-entry-type", "dir");
    await expect(feedsDir).toHaveAttribute("data-expanded", "true");
    await expect(feedsDir).toHaveAttribute("data-depth", "0");

    const devTo = treeRow(page, "dev_to.py");
    await expect(devTo).toBeVisible();
    await expect(devTo).toHaveAttribute("data-entry-type", "file");
    await expect(devTo).toHaveAttribute("data-depth", "1");
  });

  test("Enter/click on an expanded dir collapses it (children disappear); repeating re-expands", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await expect(treeRow(page, "dev_to.py")).toBeVisible();

    await treeRow(page, "feeds").click();
    await expect(treeRow(page, "feeds")).toHaveAttribute("data-expanded", "false");
    await expect(treeRow(page, "dev_to.py")).toHaveCount(0);

    await treeRow(page, "feeds").click();
    await expect(treeRow(page, "feeds")).toHaveAttribute("data-expanded", "true");
    await expect(treeRow(page, "dev_to.py")).toBeVisible();

    // Same via the keyboard — the mouse clicks above already left the
    // keyboard selection sitting on "feeds" itself, so focusing panel [2]
    // and pressing Enter toggles it again with no extra movement needed.
    // Blur first — see `blurActive`'s doc comment — the mouse clicks above
    // left real DOM focus sitting on "feeds" itself, which would otherwise
    // double-fire on the Enter below.
    await blurActive(page);
    await page.keyboard.press("2");
    await page.keyboard.press("Enter");
    await expect(treeRow(page, "feeds")).toHaveAttribute("data-expanded", "false");
    await expect(treeRow(page, "dev_to.py")).toHaveCount(0);
  });

  test("no ../ row ever appears, at the tree root or inside any subdirectory", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await expect(treeRow(page, "../")).toHaveCount(0);
    await expect(page.locator('[data-testid="repositories-tree-row"][data-entry-type="up"]')).toHaveCount(0);
  });

  test("bare j does not move the tree selection while ArrowDown does", async ({ page }) => {
    await gotoReady(page, "/repositories");
    const rows = page.locator('[data-testid="repositories-tree-row"]');
    const highlighted = /rgba\(\s*224,\s*69,\s*60,\s*0?\.18\)/;

    await expect(rows.first()).toHaveAttribute("style", highlighted);
    await expect(rows.nth(1)).not.toHaveAttribute("style", highlighted);

    await page.keyboard.press("j");
    await expect(rows.first()).toHaveAttribute("style", highlighted);
    await expect(rows.nth(1)).not.toHaveAttribute("style", highlighted);

    await page.keyboard.press("ArrowDown");
    await expect(rows.first()).not.toHaveAttribute("style", highlighted);
    await expect(rows.nth(1)).toHaveAttribute("style", highlighted);
  });

  test("tree rows render SVG folder/file icons and a ▾/▸ caret, not a plain glyph in the icon slot (Item 1)", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");

    const feedsIcon = treeRow(page, "feeds").locator('[data-testid="repositories-tree-icon"]');
    await expect(feedsIcon).toBeVisible();
    expect(await feedsIcon.innerHTML()).toContain("<svg");
    expect(await feedsIcon.innerHTML()).not.toContain("▸");

    const devToIcon = treeRow(page, "dev_to.py").locator('[data-testid="repositories-tree-icon"]');
    await expect(devToIcon).toBeVisible();
    expect(await devToIcon.innerHTML()).toContain("<svg");

    const feedsCaret = treeRow(page, "feeds").locator('[data-testid="repositories-tree-caret"]');
    await expect(feedsCaret).toHaveText("▾"); // expanded by default
    await treeRow(page, "feeds").click();
    await expect(feedsCaret).toHaveText("▸"); // collapsed
  });
});

test.describe("Repositories: panel [2] file preview + panel [0] preview", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("clicking a file previews its content in panel [0] without opening the editor", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "transcript-tts");
    await treeRow(page, "server.py").click();

    const expectedLines = fileLines("transcript-tts/server.py");
    await expect(page.locator('[data-testid="repositories-preview-line"]').first()).toContainText(expectedLines[0]);
    // Click previews only — the full-screen editor must not open.
    await expect(page.locator('[data-testid="editor-scroller"]')).toHaveCount(0);
  });

  test("Enter on a file opens the full-screen vim editor; :q returns to the tree", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "transcript-tts");
    // Click-select README.md (previews only), then focus panel [2] and press
    // Enter to open it in the editor — exercising the click-selects/
    // Enter-opens split.
    await treeRow(page, "README.md").click();
    await page.keyboard.press("2");
    await page.keyboard.press("Enter");

    const scroller = page.locator('[data-testid="editor-scroller"]');
    await expect(scroller).toBeVisible();
    const expectedFirstLine = fileLines("transcript-tts/README.md")[0];
    await expect(scroller.locator('[data-line="1"] [data-testid="editor-line-text"]')).toHaveText(expectedFirstLine);

    await page.keyboard.press(":");
    await page.keyboard.type("q");
    await page.keyboard.press("Enter");
    await expect(scroller).toHaveCount(0);
    await expect(page.locator('[data-testid="repositories-tree-row"]').first()).toBeVisible();
  });

  test("a file several levels deep in the tree previews correctly, with no descend/ascend step", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await expect(treeRow(page, "dev_to.py")).toBeVisible();

    await treeRow(page, "dev_to.py").click();
    const expectedLines = fileLines("daily-tech-digest/feeds/dev_to.py");
    await expect(page.locator('[data-testid="repositories-preview-line"]').first()).toContainText(expectedLines[0]);

    // Files panel [2] title reflects the open repo (no commit suffix — this
    // is the working tree).
    await expect(page.locator('[data-testid="repositories-panel-2"]')).toContainText("daily-tech-digest");
    await expect(page.locator('[data-testid="repositories-panel-2"]')).not.toContainText("@");
  });

  test("editor Top/%/Bot position indicator updates on Ctrl-d (long file)", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    // "tests/test_offline.py" is already visible (all dirs start expanded) —
    // no click on "tests" itself needed (that would now toggle it closed).
    await treeRow(page, "test_offline.py").click();
    await page.keyboard.press("2");
    await page.keyboard.press("Enter"); // open the previewed file in the editor

    const position = page.locator('[data-testid="editor-position"]');
    await expect(position).toContainText("Top");
    await expect(position).toContainText("1:1");

    const totalLines = fileLines("daily-tech-digest/tests/test_offline.py").length;

    await page.keyboard.press("Control+d");
    await expect(position).not.toContainText("Top 1:1");

    for (let i = 0; i < 200; i++) {
      const text = await position.innerText();
      if (text.includes("Bot")) break;
      await page.keyboard.press("Control+d");
    }
    await expect(position).toContainText("Bot");

    await page.keyboard.press("G");
    await expect(position).toContainText("Bot");
    await expect(position).toContainText(`${totalLines}:1`);
  });
});

test.describe("Repositories: panel [4] commits track ONLY panel [3] (bug fix)", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("commits stay fixed while navigating panel [2]/[0]; change only on panel [3] selection", async ({ page }) => {
    await gotoReady(page, "/repositories");
    const shaOf = () => page.locator('[data-testid="repositories-commit-row"]').first().getAttribute("data-sha8");

    // Selecting + opening daily-tech-digest via panel [3] IS a legitimate
    // panel [3] selection change, so commits update to match it once.
    await openRepoTree(page, "daily-tech-digest");
    const afterSelect = await shaOf();
    expect(afterSelect).toBeTruthy();

    // Browsing WITHIN that same repo's tree/preview — panel [2]/[0],
    // including toggling a dir's collapse state — must not move panel [4]
    // again (2026-08-17 bug report: "commits change dynamically when I move
    // across files").
    await treeRow(page, "feeds").click(); // collapses "feeds"
    await expect(shaOf()).resolves.toBe(afterSelect);
    await treeRow(page, "feeds").click(); // re-expands it
    await expect(shaOf()).resolves.toBe(afterSelect);
    await treeRow(page, "dev_to.py").click();
    await expect(shaOf()).resolves.toBe(afterSelect);
    await page.keyboard.press("0"); // focus the preview panel too
    await expect(shaOf()).resolves.toBe(afterSelect);

    // Only moving the panel [3] selection changes commits again.
    await page.keyboard.press("3");
    await page.keyboard.press("ArrowDown"); // daily-tech-digest -> transcript-tts
    await expect.poll(shaOf).not.toBe(afterSelect);
  });
});

test.describe("Repositories: commit click loads a tree (no popup); 'o' opens GitHub", () => {
  test("clicking a commit fetches its tree into panel [2] — no new tab", async ({ page, context }) => {
    const fakeTree = { sha: "deadbeef", tree: [{ path: "README.md", type: "blob" }], truncated: false };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/git/trees/**", (route) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(fakeTree) }),
    );
    await gotoReady(page, "/repositories");
    // all-projects is selected by default (Item 5) and has no commits — pick
    // daily-tech-digest explicitly to match the mocked routes above.
    await openRepoTree(page, "daily-tech-digest");

    let popupSeen = false;
    context.on("page", () => (popupSeen = true));

    await page.locator('[data-testid="repositories-commit-row"]').first().click();
    // depth 0: daily-tech-digest's OWN working tree (still momentarily
    // rendered right after the click, until the commit-tree fetch resolves)
    // also has a README.md at depth 0, so scoping by depth keeps this
    // locator unambiguous through that transient frame instead of racing a
    // strict-mode violation against the "site/README.md" depth-1 duplicate.
    await expect(treeRow(page, "README.md", 0)).toBeVisible();
    await expect(page.locator('[data-testid="repositories-panel-2"]')).toContainText(`@${dailyTechDigestHead.sha8}`);
    expect(popupSeen).toBe(false);
    expect(context.pages().length).toBe(1);
  });

  test("'o' on the selected commit opens its html_url on GitHub in a new tab", async ({ page, context }) => {
    let requestedUrl: string | null = null;
    await context.route("https://github.com/**", (route) => {
      requestedUrl = route.request().url();
      route.abort();
    });
    await context.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");

    await page.keyboard.press("4");
    await expect(page.locator('[data-testid="repositories-panel-4"]')).toHaveAttribute(
      "style",
      /border: 1px solid rgb\(224, 69, 60\)/,
    );
    const expectedHref = await page.locator('[data-testid="repositories-commit-row"]').first().getAttribute("data-html-url");
    expect(expectedHref).toMatch(COMMIT_URL_RE);

    const popupPromise = context.waitForEvent("page");
    await page.keyboard.press("o");
    const popup = await popupPromise;
    await expect.poll(() => requestedUrl).toBe(expectedHref);
    await popup.close();
  });

  test("all-projects: 'o' and Enter on the commits panel are no-ops (commit-browsing disabled)", async ({
    page,
    context,
  }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/repositories"); // all-projects is already the default selection
    await page.keyboard.press("4");

    let popupSeen = false;
    context.on("page", () => (popupSeen = true));
    await page.keyboard.press("o");
    await page.keyboard.press("Enter");
    await page.waitForTimeout(300);
    expect(popupSeen).toBe(false);
    expect(context.pages().length).toBe(1);
  });
});

test.describe("Repositories: commit-tree / file-content fetch failures preserve state", () => {
  test("commit-tree fetch failure shows a transient error and keeps the previously open tree", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "transcript-tts");
    await expect(treeRow(page, "README.md")).toBeVisible();

    // The default commits-panel abort route (registered above) also covers
    // the trees endpoint, so this commit click is guaranteed to fail.
    await page.locator('[data-testid="repositories-commit-row"]').first().click();

    await expect(page.locator('[data-testid="repositories-commit-error"]')).toBeVisible();
    // Working tree from before the failed click is still exactly what's shown.
    await expect(treeRow(page, "README.md")).toBeVisible();
    await expect(page.locator('[data-testid="repositories-panel-2"]')).not.toContainText("@");
  });

  test("commit-tree fetch 403 (rate limit) behaves the same as a network abort", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) =>
      route.fulfill({ status: 403, contentType: "application/json", body: JSON.stringify({ message: "rate limited" }) }),
    );
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await page.locator('[data-testid="repositories-commit-row"]').first().click();
    await expect(page.locator('[data-testid="repositories-commit-error"]')).toBeVisible();
  });

  test("file-content fetch failure inside a commit tree shows an error line, keeps the tree", async ({ page }) => {
    const fakeTree = { sha: "deadbeef", tree: [{ path: "README.md", type: "blob" }], truncated: false };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/git/trees/**", (route) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(fakeTree) }),
    );
    // contents/** is still covered by the broad abort above.
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await page.locator('[data-testid="repositories-commit-row"]').first().click();
    // depth 0 — see the sibling test above for why (daily-tech-digest's own
    // working tree, briefly still rendered, also has a README.md at depth 0).
    await expect(treeRow(page, "README.md", 0)).toBeVisible();

    await treeRow(page, "README.md", 0).click();
    await expect(page.locator('[data-testid="repositories-changes-body"]')).toContainText("Failed to load that file.");
    // The tree itself is untouched by the preview failure.
    await expect(treeRow(page, "README.md", 0)).toBeVisible();
  });

  test("binary/oversize file at a commit shows the binary message, not garbled content", async ({ page }) => {
    const fakeTree = { sha: "deadbeef", tree: [{ path: "asset.bin", type: "blob" }], truncated: false };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/git/trees/**", (route) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(fakeTree) }),
    );
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/contents/**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ size: 999_999, encoding: "base64", content: "" }),
      }),
    );
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await page.locator('[data-testid="repositories-commit-row"]').first().click();
    await treeRow(page, "asset.bin").click();
    await expect(page.locator('[data-testid="repositories-changes-body"]')).toContainText("Binary or too large to preview.");
  });
});

test.describe("Repositories: panel [3] spinner while a fetch is in flight", () => {
  test("spinner appears on the repo row during a delayed fetch and disappears after", async ({ page }) => {
    const fakeCommit = {
      sha: "deadbeef00001111222233334444555566667777",
      commit: { message: "fake live commit for e2e", author: { name: "Test Bot" } },
      author: { login: "TestBot" },
      html_url: "https://github.com/ShevinuM/daily-tech-digest/commit/deadbeef00001111222233334444555566667777",
    };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/commits**", async (route) => {
      await new Promise((r) => setTimeout(r, 500));
      await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify([fakeCommit]) });
    });

    await gotoReady(page, "/repositories");
    // all-projects is the default selection now (Item 5) and never triggers
    // a live-commits fetch — select daily-tech-digest explicitly to match
    // the delayed route above.
    await page.locator('[data-testid="repositories-repo-row"][data-repo-name="daily-tech-digest"]').click();
    const spinner = page.locator('[data-testid="repositories-repo-spinner"]');
    await expect(spinner).toBeVisible();
    await expect(spinner).toHaveCount(0, { timeout: 5000 });
  });
});

test.describe("Repositories: commit row heights render at full glyph height", () => {
  test("15 live-mocked commits render unclipped rows at 1512x945", async ({ page }) => {
    await page.setViewportSize({ width: 1512, height: 945 });
    const fakeCommits = Array.from({ length: 15 }, (_, i) => ({
      sha: `${i.toString(16).padStart(2, "0")}${"deadbeefcafefeed1234567890abcdef123456".slice(2)}`,
      commit: { message: `fake commit number ${i} with a reasonably long message`, author: { name: "Test Bot" } },
      author: { login: "TestBot" },
      html_url: `https://github.com/ShevinuM/daily-tech-digest/commit/fake${i}`,
    }));
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/commits**", (route) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(fakeCommits) }),
    );

    await gotoReady(page, "/repositories");
    await page.locator('[data-testid="repositories-repo-row"][data-repo-name="daily-tech-digest"]').click();
    const rows = page.locator('[data-testid="repositories-commit-row"]');
    await expect(rows).toHaveCount(15);
    // Root cause of the flake this replaces: `commits` (Repositories.svelte) is
    // `liveCommits[repo.key] ?? commitsByRepo[repo.key] ?? []` — clicking
    // the repo row FIRST renders the committed static snapshot (which,
    // coincidentally, also currently has exactly 15 real commits for
    // daily-tech-digest), then swaps to this test's mocked `liveCommits`
    // once the fetch above resolves. Both states satisfy `toHaveCount(15)`,
    // so that assertion alone can resolve during either one; the keyed
    // `{#each commits as c (c.sha8)}` block has no shas in common between
    // the two states, so the swap removes and recreates all 15 row
    // elements, and measuring mid-swap caught freshly-inserted nodes before
    // a style/layout pass applied their scoped CSS (0 height, unparsed
    // "normal" line-height). Waiting for the mocked commits' own text
    // (absent from the real static snapshot) proves the swap is over
    // before any row is measured, rather than racing it with a sleep.
    await expect(rows.first()).toContainText("fake commit number");

    const measurements = await rows.evaluateAll((els) =>
      els.map((el) => {
        const rect = el.getBoundingClientRect();
        const lineHeight = parseFloat(getComputedStyle(el).lineHeight);
        return { height: rect.height, lineHeight };
      }),
    );
    for (const { height, lineHeight } of measurements) {
      // A clipped/overlapping row (the reported bug) renders shorter than
      // its own computed line-height; a full-height row never does.
      expect(height).toBeGreaterThanOrEqual(lineHeight - 0.5);
    }
  });
});

test.describe("Repositories: t is not bound", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("t from repositories does nothing — Retina-V is reachable only via Ctrl-b 3 or a click", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await page.keyboard.press("t");
    await expect(page).toHaveURL(/\/repositories$/);
  });
});

test.describe("Repositories: panel focus border (panels 0 and 1)", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("0 focuses the Changes panel (border); 1 focuses the Status panel (border)", async ({ page }) => {
    await gotoReady(page, "/repositories");
    const FOCUSED = /border: 1px solid rgb\(224, 69, 60\)/;
    const UNFOCUSED = /border: 1px solid rgba\(224, 69, 60, 0\.35\)/;

    await page.keyboard.press("0");
    await expect(page.locator('[data-testid="repositories-panel-0"]')).toHaveAttribute("style", FOCUSED);
    await expect(page.locator('[data-testid="repositories-panel-2"]')).toHaveAttribute("style", UNFOCUSED);

    await page.keyboard.press("1");
    await expect(page.locator('[data-testid="repositories-panel-1"]')).toHaveAttribute("style", FOCUSED);
    await expect(page.locator('[data-testid="repositories-panel-0"]')).toHaveAttribute("style", UNFOCUSED);
  });
});

test.describe("Repositories: client-side commit refresh (panel [3] selection only)", () => {
  // daily-tech-digest is not the default-selected repo (all-projects is),
  // so every test here explicitly selects it first to match its own
  // committed snapshot head (`dailyTechDigestHead`
  // above, loaded — not hardcoded — from src/generated/commits/
  // daily-tech-digest.json, so a `pnpm generate` refresh can't break this).
  test("route-fulfill with a fake commit replaces the snapshot list for the selected repo", async ({ page }) => {
    const fakeCommit = {
      sha: "deadbeef00001111222233334444555566667777",
      commit: { message: "fake live commit for e2e\n\nbody text", author: { name: "Test Bot" } },
      author: { login: "TestBot" },
      html_url: "https://github.com/ShevinuM/daily-tech-digest/commit/deadbeef00001111222233334444555566667777",
    };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/commits**", (route) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify([fakeCommit]) }),
    );

    await gotoReady(page, "/repositories");
    await page.locator('[data-testid="repositories-repo-row"][data-repo-name="daily-tech-digest"]').click();
    await expect
      .poll(async () => page.locator('[data-testid="repositories-commit-row"]').first().getAttribute("data-sha8"), {
        timeout: 5000,
      })
      .toBe("deadbeef");
  });

  test("route-abort keeps the committed snapshot list intact", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/repositories");
    await page.locator('[data-testid="repositories-repo-row"][data-repo-name="daily-tech-digest"]').click();
    await page.waitForTimeout(500);
    await expect(page.locator('[data-testid="repositories-commit-row"]').first()).toHaveAttribute(
      "data-sha8",
      dailyTechDigestHead.sha8,
    );
  });

  test("API 403 keeps the committed snapshot list intact", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) =>
      route.fulfill({ status: 403, contentType: "application/json", body: JSON.stringify({ message: "API rate limit exceeded" }) }),
    );
    await gotoReady(page, "/repositories");
    await page.locator('[data-testid="repositories-repo-row"][data-repo-name="daily-tech-digest"]').click();
    await page.waitForTimeout(500);
    await expect(page.locator('[data-testid="repositories-commit-row"]').first()).toHaveAttribute(
      "data-sha8",
      dailyTechDigestHead.sha8,
    );
  });
});

test.describe("Repositories: editor statusline stays a single line", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("statusline height is identical for a short breadcrumb and a long nested-path breadcrumb", async ({ page }) => {
    // A full 1512/1920px-wide statusline never runs out of room for either
    // breadcrumb below, so the height comparison would pass trivially even
    // without the item-14 fix (min-width:0/nowrap/ellipsis on the breadcrumb
    // span). Narrow the viewport so the long, deeply-nested path genuinely
    // exceeds the available flex space and would wrap onto a 2nd line under
    // the OLD (unfixed) markup — only the fix's ellipsis keeps it single-line
    // here.
    // Below 900px width the app's desktop/fine-pointer gate
    // (Terminal.svelte's `matchMedia("(min-width: 900px)...")`) never
    // attaches keyboard listeners at all, so this stays just above that
    // floor while still being narrow enough to force the discrimination
    // described above.
    await page.setViewportSize({ width: 900, height: 700 });
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");

    // Short breadcrumb baseline: "daily-tech-digest › README.md" (depth 0 —
    // daily-tech-digest also has a nested "site/README.md", now
    // simultaneously visible in the fully-expanded tree, so this needs
    // disambiguating).
    await treeRow(page, "README.md", 0).click();
    await page.keyboard.press("2");
    await page.keyboard.press("Enter");
    const statusline = page.locator('[data-testid="editor-statusline"]');
    await expect(statusline).toBeVisible();
    const shortHeight = (await statusline.boundingBox())!.height;

    await page.keyboard.press(":");
    await page.keyboard.type("q");
    await page.keyboard.press("Enter");
    await expect(page.locator('[data-testid="editor-scroller"]')).toHaveCount(0);

    // Long breadcrumb: switch repos to Data-Structures-And-Algorithms and
    // open its longest real path — "Sorting Algorithms/avaerage_salary_
    // excluding_the_minimum_and_maximum_salary.py" — read straight off disk
    // like every other assertion in this suite, so this can't drift from the
    // fixture repo's actual content. Its single unbreakable filename alone
    // (61 chars) exceeds the available flex space at ANY viewport width the
    // desktop-mode gate allows (900px+), unlike a shorter nested path that
    // can coincidentally still fit on one line even when narrowed — this one
    // reliably forces a 2nd line under the OLD (unfixed) markup.
    const longFileName = "avaerage_salary_excluding_the_minimum_and_maximum_salary.py";
    const longPath = `Sorting Algorithms/${longFileName}`;
    expect(fileLines(`Data-Structures-And-Algorithms/${longPath}`).length).toBeGreaterThan(0);
    await openRepoTree(page, "Data-Structures-And-Algorithms");
    await treeRow(page, longFileName).click();
    await page.keyboard.press("2");
    await page.keyboard.press("Enter");
    await expect(statusline).toBeVisible();
    const longHeight = (await statusline.boundingBox())!.height;

    // Equal height (within a hairline of rounding) proves the long-path
    // breadcrumb truncated/ellipsized instead of wrapping onto a 2nd line.
    expect(Math.abs(longHeight - shortHeight)).toBeLessThan(2);
  });
});
