// Behavioral e2e suite for the Repositories (lazygit) view, against the real (non-fixture) content build — exactly 8 real repos, each with 1 repo, plus the virtual all-projects entry pinned first and selected by default (daily-tech-digest is therefore idx 1, not idx 0).
//
// Panel [2]'s Files pane is a lazygit-style tree: the full nested tree renders at once, every dir starts expanded, and click/Enter on a dir toggles collapse in place without ever changing the selected repo or what panel [4] shows.
//
// Commit snapshots and repo file indexes are generated by scripts/generate.mjs from SHA-pinned GitHub tarballs and the real GitHub API and are live-refreshable, so `loadCommitSnapshot()`/`dailyTechDigestHead` parse the checked-in JSON at test time rather than hardcoding a sha.
import type { Locator } from "@playwright/test";
import { expect, test, type Page } from "../../../../../common/tests/ui/support/fixtures";
// The shared `fixtures.ts` `context` fixture pre-seeds the boot-seen flag so BootSequence's ~4.6s sequence never runs for these tests.
import { readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "../../../../../..");

async function gotoReady(page: Page, path: string) {
  await page.goto(path);
  await page.locator('[data-terminal-ready="true"]').waitFor({ state: "attached" });
}

/** Reads a real file straight off disk, from the SHA-pinned tarball cache generate.mjs populates at `.cache/repos/<name>-<sha>/`, so assertions check against ground truth independent of generate.mjs's own read/tokenize path. */
function fileLines(repoRelativePath: string): string[] {
  const slash = repoRelativePath.indexOf("/");
  const repoName = repoRelativePath.slice(0, slash);
  const rest = repoRelativePath.slice(slash + 1);
  const pins = JSON.parse(readFileSync(join(ROOT, "repos.json"), "utf8")) as Record<string, string>;
  const sha = pins[repoName];
  return readFileSync(join(ROOT, ".cache/repos", `${repoName}-${sha}`, rest), "utf8").split("\n");
}

interface CommitSnapshotEntry {
  sha: string;
  sha8: string;
  msg: string;
  html_url: string;
  initials: string;
}

/** The committed snapshot Repositories.svelte falls back to on a failed live fetch, parsed at test time rather than a hardcoded sha8 so a `pnpm generate` refresh can never break these assertions. */
function loadCommitSnapshot(repo: string): CommitSnapshotEntry[] {
  return JSON.parse(
    readFileSync(join(ROOT, "src/generated/commits", `${repo}.json`), "utf8"),
  ) as CommitSnapshotEntry[];
}

/** The head commit of daily-tech-digest's own committed snapshot; every "keeps the committed snapshot intact" assertion below checks against this rather than a hardcoded sha. */
const dailyTechDigestHead = loadCommitSnapshot("daily-tech-digest")[0];

const COMMIT_URL_RE =
  /^https:\/\/github\.com\/ShevinuM\/(daily-tech-digest|transcript-tts|Legend-of-Arlo-Guardians-Gauntlet|SpotifyPal|Advent-of-Code-2024|Advent-Of-Code-2023|Sheldon|Data-Structures-And-Algorithms)\/commit\/[0-9a-f]{7,40}$/;

/** Clicks a panel [1] repo row (selects it and loads its tree, no separate open step) and waits for the tree to actually render, since the working-tree index fetch is asynchronous. */
async function openRepoTree(page: Page, repoName: string) {
  await page.locator(`[data-testid="repositories-repo-row"][data-repo-name="${repoName}"]`).click();
  await expect(page.locator('[data-testid="repositories-tree-row"]').first()).toBeVisible();
}

/** Matches tree rows by name; pass `depth` to disambiguate when the same
 * filename appears more than once in a tree at different nesting levels
 * (daily-tech-digest genuinely has this — both `README.md` at the repo root
 * AND `site/README.md`, now simultaneously visible since the whole tree
 * renders at once). */
function treeRow(page: Page, name: string, depth?: number) {
  const depthSelector = depth === undefined ? "" : `[data-depth="${depth}"]`;
  return page.locator(
    `[data-testid="repositories-tree-row"][data-entry-name="${name}"]${depthSelector}`,
  );
}

/** The badge drawn on Repositories pane `n`. */
function paneBadge(page: Page, n: number) {
  return page.getByTestId(`repositories-panel-${n}`).getByTestId("panel-badge");
}

const REPO_FILL = "rgba(224, 69, 60, 0.22)";
const TREE_FILL = "rgba(74, 159, 224, 0.16)";
const COMMIT_FILL = "rgba(224, 69, 60, 0.2)";
/** Selected repo and tree rows switch to this text colour. */
const SELECTED_TEXT = "rgb(244, 236, 233)";

/** Asserts a row is drawn selected: `data-selected`, a solid `fill`, no gradient, and (unless `gutter` is false) a transparent 2px left gutter. */
async function expectSelectedRow(row: Locator, fill: string, opts: { gutter?: boolean } = {}) {
  await expect(row).toHaveAttribute("data-selected", "");
  await expect(row).toHaveCSS("background-color", fill);
  await expect(row).toHaveCSS("background-image", "none");
  if (opts.gutter === false) return;
  await expect(row).toHaveCSS("border-left-color", "rgba(0, 0, 0, 0)");
  await expect(row).toHaveCSS("border-left-width", "2px");
}

/** Asserts a row is drawn unselected: no `data-selected` and a transparent background. */
async function expectUnselectedRow(row: Locator) {
  await expect(row).not.toHaveAttribute("data-selected");
  await expect(row).toHaveCSS("background-color", "rgba(0, 0, 0, 0)");
}

/** The viewport x of an element's left edge. */
function leftOf(el: Locator): Promise<number> {
  return el.evaluate((node) => node.getBoundingClientRect().left);
}

async function ctrlB(page: Page) {
  await page.keyboard.down("Control");
  await page.keyboard.press("b");
  await page.keyboard.up("Control");
}

/** Clicking a row leaves real DOM focus on it, so a later keyboard-driven selection change without a blur would hit that row's own stale Enter handler before Terminal's global listener sees it. */
async function blurActive(page: Page) {
  await page.evaluate(() => (document.activeElement as HTMLElement | null)?.blur());
}

test.describe("Repositories: panel [1] repo list — all-projects pinned first + default-selected", () => {
  test.beforeEach(async ({ context }) => {
    // Default for every test in this file: no real network call to GitHub.
    //
    // Tests that specifically exercise the mocked fulfill/abort paths
    // override this per-test/per-page (Playwright resolves the
    // most-recently-registered matching route first).
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("all-projects is row 0; the 8 real repos follow in frontmatter order (Item 5)", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    const rows = page.locator('[data-testid="repositories-repo-row"]');
    await expect(rows).toHaveCount(9);
    const names = await rows.evaluateAll((els) =>
      els.map((el) => el.getAttribute("data-repo-name")),
    );
    expect(names).toEqual([
      "all-projects",
      "daily-tech-digest",
      "transcript-tts",
      "Legend-of-Arlo-Guardians-Gauntlet",
      "SpotifyPal",
      "Advent-of-Code-2024",
      "Advent-Of-Code-2023",
      "Sheldon",
      "Data-Structures-And-Algorithms",
    ]);
    await expect(rows.first()).toHaveAttribute("data-all-projects", "true");
    for (let i = 1; i < 9; i++) {
      await expect(rows.nth(i)).toHaveAttribute("data-all-projects", "false");
    }
  });

  test("Files pane shows the all-projects tree on mount — no click or keypress needed (Item 5)", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    await expect(page.locator('[data-testid="repositories-tree-row"]').first()).toBeVisible();
    await expect(page.locator('[data-testid="repositories-panel-2"]')).toContainText(
      "all-projects",
    );

    const names = await page
      .locator('[data-testid="repositories-tree-row"]')
      .evaluateAll((els) => els.map((el) => el.getAttribute("data-entry-name")));
    expect(names.sort()).toEqual(
      [
        "daily-tech-digest.md",
        "transcript-tts.md",
        "Legend-of-Arlo-Guardians-Gauntlet.md",
        "SpotifyPal.md",
        "Advent-of-Code-2024.md",
        "Advent-Of-Code-2023.md",
        "Sheldon.md",
        "Data-Structures-And-Algorithms.md",
      ].sort(),
    );

    // "Loaded" isn't the same claim as "selected" — confirm row 0 (all-projects) already carries the selection with zero j/k presses.
    await page.keyboard.press("1");
    const repoRows = page.getByTestId("repositories-repo-row");
    await expect(repoRows.and(page.locator("[data-selected]"))).toHaveCount(1);
    await expect(repoRows.first()).toHaveAttribute("data-repo-name", "all-projects");
    await expectSelectedRow(repoRows.first(), REPO_FILL);
  });

  test("ArrowDown moves the solid repo fill to the next row", async ({ page }) => {
    await gotoReady(page, "/repositories");
    const repoRows = page.getByTestId("repositories-repo-row");
    await page.keyboard.press("1");
    await page.keyboard.press("ArrowDown");
    await expect(repoRows.nth(1)).toHaveAttribute("data-repo-name", "daily-tech-digest");
    await expectSelectedRow(repoRows.nth(1), REPO_FILL);
    await expectUnselectedRow(repoRows.first());
  });

  test("clicking a different repo row swaps panel [2] over to that repo's tree", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    await expect(page.locator('[data-testid="repositories-panel-2"]')).toContainText(
      "all-projects",
    );

    await openRepoTree(page, "transcript-tts");
    await expect(treeRow(page, "README.md")).toBeVisible();
    await expect(page.locator('[data-testid="repositories-panel-2"]')).toContainText(
      "transcript-tts",
    );
    await expect(page.locator('[data-testid="repositories-panel-2"]')).not.toContainText(
      "all-projects",
    );
  });

  test("Enter on the highlighted repo row also loads its tree (keyboard path)", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    // Move off the mount-time default (all-projects) first so pressing
    // Enter below is actually exercising the keyboard path, not just
    // observing what was already loaded on mount.
    await openRepoTree(page, "transcript-tts");
    await expect(treeRow(page, "README.md")).toBeVisible();

    await blurActive(page); // see helper doc — avoids a stale-focus double-fire on Enter below
    await page.keyboard.press("1");
    await expect(paneBadge(page, 1)).toHaveAttribute("data-focused", "");
    await page.keyboard.press("ArrowUp"); // wrap from transcript-tts (idx 2) back to all-projects (idx 0)
    await page.keyboard.press("ArrowUp");
    await page.keyboard.press("Enter");
    await expect(treeRow(page, "daily-tech-digest.md")).toBeVisible();
    await expect(treeRow(page, "README.md")).toHaveCount(0);
  });

  test("all-projects lists all 8 real project .md files", async ({ page }) => {
    await gotoReady(page, "/repositories");
    const rows = page.locator('[data-testid="repositories-tree-row"]');
    const names = await rows.evaluateAll((els) =>
      els.map((el) => el.getAttribute("data-entry-name")),
    );
    expect(names.sort()).toEqual(
      [
        "daily-tech-digest.md",
        "transcript-tts.md",
        "Legend-of-Arlo-Guardians-Gauntlet.md",
        "SpotifyPal.md",
        "Advent-of-Code-2024.md",
        "Advent-Of-Code-2023.md",
        "Sheldon.md",
        "Data-Structures-And-Algorithms.md",
      ].sort(),
    );
    // all-projects is a flat doc bundle — no directories in its tree.
    await expect(
      page.locator('[data-testid="repositories-tree-row"][data-entry-type="dir"]'),
    ).toHaveCount(0);
  });

  test("all-projects: commits panel shows the data-driven local-only line, not commit rows", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    await page.keyboard.press("1");
    await page
      .locator('[data-testid="repositories-repo-row"][data-repo-name="all-projects"]')
      .click();
    await expectSelectedRow(
      page.locator('[data-testid="repositories-repo-row"][data-all-projects="true"]'),
      REPO_FILL,
    );
    await expect(page.locator('[data-testid="repositories-commit-row"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="repositories-panel-4"]')).toContainText("local only");
  });
});

test.describe("Repositories: panel [2] lazygit-style tree — expand/collapse, no ../ row (Item 4)", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("a known subdir's children render immediately on load — no click needed to descend", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");

    // "feeds" is a real subdirectory of daily-tech-digest with several
    // files in it; all of them must already be visible without ever
    // clicking "feeds" itself.
    const feedsDir = treeRow(page, "feeds");
    await expect(feedsDir).toBeVisible();
    await expect(feedsDir).toHaveAttribute("data-entry-type", "dir");
    await expect(feedsDir).toHaveAttribute("data-expanded", "true");
    await expect(feedsDir).toHaveAttribute("data-depth", "0");

    const devTo = treeRow(page, "dev_to.py");
    await expect(devTo).toBeVisible();
    await expect(devTo).toHaveAttribute("data-entry-type", "file");
    await expect(devTo).toHaveAttribute("data-depth", "1");
  });

  test("Enter/click on an expanded dir collapses it (children disappear); repeating re-expands", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await expect(treeRow(page, "dev_to.py")).toBeVisible();

    await treeRow(page, "feeds").click();
    await expect(treeRow(page, "feeds")).toHaveAttribute("data-expanded", "false");
    await expect(treeRow(page, "dev_to.py")).toHaveCount(0);

    await treeRow(page, "feeds").click();
    await expect(treeRow(page, "feeds")).toHaveAttribute("data-expanded", "true");
    await expect(treeRow(page, "dev_to.py")).toBeVisible();

    // Same via the keyboard — the mouse clicks above already left the
    // keyboard selection sitting on "feeds" itself, so focusing panel [2]
    // and pressing Enter toggles it again with no extra movement needed.
    //
    // Blur first — see `blurActive`'s doc comment — the mouse clicks above
    // left real DOM focus sitting on "feeds" itself, which would otherwise
    // double-fire on the Enter below.
    await blurActive(page);
    await page.keyboard.press("2");
    await page.keyboard.press("Enter");
    await expect(treeRow(page, "feeds")).toHaveAttribute("data-expanded", "false");
    await expect(treeRow(page, "dev_to.py")).toHaveCount(0);
  });

  test("no ../ row ever appears, at the tree root or inside any subdirectory", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await expect(treeRow(page, "../")).toHaveCount(0);
    await expect(
      page.locator('[data-testid="repositories-tree-row"][data-entry-type="up"]'),
    ).toHaveCount(0);
  });

  test("bare j does not move the tree selection while ArrowDown does", async ({ page }) => {
    await gotoReady(page, "/repositories");
    const rows = page.locator('[data-testid="repositories-tree-row"]');

    await expectSelectedRow(rows.first(), TREE_FILL);
    await expectUnselectedRow(rows.nth(1));

    await page.keyboard.press("j");
    await expectSelectedRow(rows.first(), TREE_FILL);
    await expectUnselectedRow(rows.nth(1));

    await page.keyboard.press("ArrowDown");
    await expectUnselectedRow(rows.first());
    await expectSelectedRow(rows.nth(1), TREE_FILL);
  });

  test("tree rows render SVG folder/file icons and a ▾/▸ caret, not a plain glyph in the icon slot (Item 1)", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");

    const feedsIcon = treeRow(page, "feeds").locator('[data-testid="repositories-tree-icon"]');
    await expect(feedsIcon).toBeVisible();
    expect(await feedsIcon.innerHTML()).toContain("<svg");
    expect(await feedsIcon.innerHTML()).not.toContain("▸");

    const devToIcon = treeRow(page, "dev_to.py").locator('[data-testid="repositories-tree-icon"]');
    await expect(devToIcon).toBeVisible();
    expect(await devToIcon.innerHTML()).toContain("<svg");

    const feedsCaret = treeRow(page, "feeds").locator('[data-testid="repositories-tree-caret"]');
    await expect(feedsCaret).toHaveText("▾"); // expanded by default
    await treeRow(page, "feeds").click();
    await expect(feedsCaret).toHaveText("▸"); // collapsed
  });
});

test.describe("Repositories: panel [2] file preview + panel [3] preview", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("clicking a file previews its content in panel [3] without opening the editor", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "transcript-tts");
    await treeRow(page, "server.py").click();

    const expectedLines = fileLines("transcript-tts/server.py");
    await expect(page.locator('[data-testid="repositories-preview-line"]').first()).toContainText(
      expectedLines[0],
    );
    // Click previews only — the full-screen editor must not open.
    await expect(page.locator('[data-testid="editor-scroller"]')).toHaveCount(0);
  });

  test("Enter on a file opens the full-screen vim editor; :q returns to the tree", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "transcript-tts");
    // Click-select README.md (previews only), then focus panel [2] and press
    // Enter to open it in the editor — exercising the click-selects/
    // Enter-opens split.
    await treeRow(page, "README.md").click();
    await page.keyboard.press("2");
    await page.keyboard.press("Enter");

    const scroller = page.locator('[data-testid="editor-scroller"]');
    await expect(scroller).toBeVisible();
    const expectedFirstLine = fileLines("transcript-tts/README.md")[0];
    await expect(scroller.locator('[data-line="1"] [data-testid="editor-line-text"]')).toHaveText(
      expectedFirstLine,
    );

    await page.keyboard.press(":");
    await page.keyboard.type("q");
    await page.keyboard.press("Enter");
    await expect(scroller).toHaveCount(0);
    await expect(page.locator('[data-testid="repositories-tree-row"]').first()).toBeVisible();
  });

  test("a file several levels deep in the tree previews correctly, with no descend/ascend step", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await expect(treeRow(page, "dev_to.py")).toBeVisible();

    await treeRow(page, "dev_to.py").click();
    const expectedLines = fileLines("daily-tech-digest/feeds/dev_to.py");
    await expect(page.locator('[data-testid="repositories-preview-line"]').first()).toContainText(
      expectedLines[0],
    );

    // Files panel [2] title reflects the open repo (no commit suffix — this
    // is the working tree).
    await expect(page.locator('[data-testid="repositories-panel-2"]')).toContainText(
      "daily-tech-digest",
    );
    await expect(page.locator('[data-testid="repositories-panel-2"]')).not.toContainText("@");
  });

  test("editor Top/%/Bot position indicator updates on Ctrl-d (long file)", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    // "tests/test_offline.py" is already visible (all dirs start expanded) —
    // no click on "tests" itself needed (that would now toggle it closed).
    await treeRow(page, "test_offline.py").click();
    await page.keyboard.press("2");
    await page.keyboard.press("Enter"); // open the previewed file in the editor

    const position = page.locator('[data-testid="editor-position"]');
    await expect(position).toContainText("Top");
    await expect(position).toContainText("1:1");

    const totalLines = fileLines("daily-tech-digest/tests/test_offline.py").length;

    await page.keyboard.press("Control+d");
    await expect(position).not.toContainText("Top 1:1");

    for (let i = 0; i < 200; i++) {
      const text = await position.innerText();
      if (text.includes("Bot")) break;
      await page.keyboard.press("Control+d");
    }
    await expect(position).toContainText("Bot");

    await page.keyboard.press("G");
    await expect(position).toContainText("Bot");
    await expect(position).toContainText(`${totalLines}:1`);
  });
});

test.describe("Repositories: panel [4] commits track ONLY panel [1] (bug fix)", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("commits stay fixed while navigating panel [2]/[3]; change only on panel [1] selection", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    const shaOf = () =>
      page.locator('[data-testid="repositories-commit-row"]').first().getAttribute("data-sha8");

    // Selecting + opening daily-tech-digest via panel [1] IS a legitimate
    // panel [1] selection change, so commits update to match it once.
    await openRepoTree(page, "daily-tech-digest");
    const afterSelect = await shaOf();
    expect(afterSelect).toBeTruthy();

    // Browsing WITHIN that same repo's tree/preview — panel [2]/[3],
    // including toggling a dir's collapse state — must not move panel [4] again.
    await treeRow(page, "feeds").click();
    await expect(shaOf()).resolves.toBe(afterSelect);
    await treeRow(page, "feeds").click();
    await expect(shaOf()).resolves.toBe(afterSelect);
    await treeRow(page, "dev_to.py").click();
    await expect(shaOf()).resolves.toBe(afterSelect);
    await page.keyboard.press("3"); // focus the preview (Content) panel too
    await expect(shaOf()).resolves.toBe(afterSelect);

    // Only moving the panel [1] selection changes commits again.
    await page.keyboard.press("1");
    await page.keyboard.press("ArrowDown"); // daily-tech-digest -> transcript-tts
    await expect.poll(shaOf).not.toBe(afterSelect);
  });

  test("the commit fill shows only while pane 4 has focus", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await blurActive(page);
    const commitRows = page.getByTestId("repositories-commit-row");

    await page.keyboard.press("4");
    // Commit rows sit on the spine and have no gutter.
    await expectSelectedRow(commitRows.first(), COMMIT_FILL, { gutter: false });
    await expect(commitRows.first()).toHaveCSS("border-left-width", "0px");

    await page.keyboard.press("2");
    await expect(commitRows.and(page.locator("[data-selected]"))).toHaveCount(0);
    await expect(commitRows.first()).toHaveCSS("background-color", "rgba(0, 0, 0, 0)");
  });
});

test.describe("Repositories: commit click loads a tree (no popup); 'o' opens GitHub", () => {
  test("clicking a commit fetches its tree into panel [2] — no new tab", async ({
    page,
    context,
  }) => {
    const fakeTree = {
      sha: "deadbeef",
      tree: [{ path: "README.md", type: "blob" }],
      truncated: false,
    };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/git/trees/**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(fakeTree),
      }),
    );
    await gotoReady(page, "/repositories");
    // all-projects is selected by default and has no commits — pick
    // daily-tech-digest explicitly to match the mocked routes above.
    await openRepoTree(page, "daily-tech-digest");

    let popupSeen = false;
    context.on("page", () => (popupSeen = true));

    await page.locator('[data-testid="repositories-commit-row"]').first().click();
    // depth 0: daily-tech-digest's OWN working tree (still momentarily
    // rendered right after the click, until the commit-tree fetch resolves)
    // also has a README.md at depth 0, so scoping by depth keeps this
    // locator unambiguous through that transient frame instead of racing a
    // strict-mode violation against the "site/README.md" depth-1 duplicate.
    await expect(treeRow(page, "README.md", 0)).toBeVisible();
    await expect(page.locator('[data-testid="repositories-panel-2"]')).toContainText(
      `@${dailyTechDigestHead.sha8}`,
    );
    expect(popupSeen).toBe(false);
    expect(context.pages().length).toBe(1);
  });

  test("'o' on the selected commit opens its html_url on GitHub in a new tab", async ({
    page,
    context,
  }) => {
    let requestedUrl: string | null = null;
    await context.route("https://github.com/**", (route) => {
      requestedUrl = route.request().url();
      route.abort();
    });
    await context.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");

    await page.keyboard.press("4");
    await expect(paneBadge(page, 4)).toHaveAttribute("data-focused", "");
    const expectedHref = await page
      .locator('[data-testid="repositories-commit-row"]')
      .first()
      .getAttribute("data-html-url");
    expect(expectedHref).toMatch(COMMIT_URL_RE);

    const popupPromise = context.waitForEvent("page");
    await page.keyboard.press("o");
    const popup = await popupPromise;
    await expect.poll(() => requestedUrl).toBe(expectedHref);
    await popup.close();
  });

  test("all-projects: 'o' and Enter on the commits panel are no-ops (commit-browsing disabled)", async ({
    page,
    context,
  }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/repositories"); // all-projects is already the default selection
    await page.keyboard.press("4");

    let popupSeen = false;
    context.on("page", () => (popupSeen = true));
    await page.keyboard.press("o");
    await page.keyboard.press("Enter");
    await page.waitForTimeout(300);
    expect(popupSeen).toBe(false);
    expect(context.pages().length).toBe(1);
  });
});

test.describe("Repositories: commit-tree / file-content fetch failures preserve state", () => {
  test("commit-tree fetch failure shows a transient error and keeps the previously open tree", async ({
    page,
  }) => {
    await page.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "transcript-tts");
    await expect(treeRow(page, "README.md")).toBeVisible();

    // The default commits-panel abort route (registered above) also covers
    // the trees endpoint, so this commit click is guaranteed to fail.
    await page.locator('[data-testid="repositories-commit-row"]').first().click();

    await expect(page.locator('[data-testid="repositories-commit-error"]')).toBeVisible();
    // Working tree from before the failed click is still exactly what's shown.
    await expect(treeRow(page, "README.md")).toBeVisible();
    await expect(page.locator('[data-testid="repositories-panel-2"]')).not.toContainText("@");
  });

  test("commit-tree fetch 403 (rate limit) behaves the same as a network abort", async ({
    page,
  }) => {
    await page.route("**/api.github.com/**", (route) =>
      route.fulfill({
        status: 403,
        contentType: "application/json",
        body: JSON.stringify({ message: "rate limited" }),
      }),
    );
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await page.locator('[data-testid="repositories-commit-row"]').first().click();
    await expect(page.locator('[data-testid="repositories-commit-error"]')).toBeVisible();
  });

  test("file-content fetch failure inside a commit tree shows an error line, keeps the tree", async ({
    page,
  }) => {
    const fakeTree = {
      sha: "deadbeef",
      tree: [{ path: "README.md", type: "blob" }],
      truncated: false,
    };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/git/trees/**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(fakeTree),
      }),
    );
    // contents/** is still covered by the broad abort above.
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await page.locator('[data-testid="repositories-commit-row"]').first().click();
    // depth 0 — see the sibling test above for why (daily-tech-digest's own
    // working tree, briefly still rendered, also has a README.md at depth 0).
    await expect(treeRow(page, "README.md", 0)).toBeVisible();

    await treeRow(page, "README.md", 0).click();
    await expect(page.locator('[data-testid="repositories-changes-body"]')).toContainText(
      "Failed to load that file.",
    );
    // The tree itself is untouched by the preview failure.
    await expect(treeRow(page, "README.md", 0)).toBeVisible();
  });

  test("binary/oversize file at a commit shows the binary message, not garbled content", async ({
    page,
  }) => {
    const fakeTree = {
      sha: "deadbeef",
      tree: [{ path: "asset.bin", type: "blob" }],
      truncated: false,
    };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/git/trees/**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(fakeTree),
      }),
    );
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/contents/**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ size: 999_999, encoding: "base64", content: "" }),
      }),
    );
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await page.locator('[data-testid="repositories-commit-row"]').first().click();
    await treeRow(page, "asset.bin").click();
    await expect(page.locator('[data-testid="repositories-changes-body"]')).toContainText(
      "Binary or too large to preview.",
    );
  });
});

test.describe("Repositories: panel [1] spinner while a fetch is in flight", () => {
  test("spinner appears on the repo row during a delayed fetch and disappears after", async ({
    page,
  }) => {
    const fakeCommit = {
      sha: "deadbeef00001111222233334444555566667777",
      commit: { message: "fake live commit for e2e", author: { name: "Test Bot" } },
      author: { login: "TestBot" },
      html_url:
        "https://github.com/ShevinuM/daily-tech-digest/commit/deadbeef00001111222233334444555566667777",
    };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route(
      "**/api.github.com/repos/ShevinuM/daily-tech-digest/commits**",
      async (route) => {
        await new Promise((r) => setTimeout(r, 500));
        await route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify([fakeCommit]),
        });
      },
    );

    await gotoReady(page, "/repositories");
    // all-projects is the default selection and never triggers
    // a live-commits fetch — select daily-tech-digest explicitly to match
    // the delayed route above.
    await page
      .locator('[data-testid="repositories-repo-row"][data-repo-name="daily-tech-digest"]')
      .click();
    const spinner = page.locator('[data-testid="repositories-repo-spinner"]');
    await expect(spinner).toBeVisible();
    await expect(spinner).toHaveCount(0, { timeout: 5000 });
  });
});

test.describe("Repositories: commit row heights render at full glyph height", () => {
  test("15 live-mocked commits render unclipped rows at 1512x945", async ({ page }) => {
    await page.setViewportSize({ width: 1512, height: 945 });
    const fakeCommits = Array.from({ length: 15 }, (_, i) => ({
      sha: `${i.toString(16).padStart(2, "0")}${"deadbeefcafefeed1234567890abcdef123456".slice(2)}`,
      commit: {
        message: `fake commit number ${i} with a reasonably long message`,
        author: { name: "Test Bot" },
      },
      author: { login: "TestBot" },
      html_url: `https://github.com/ShevinuM/daily-tech-digest/commit/fake${i}`,
    }));
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/commits**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(fakeCommits),
      }),
    );

    await gotoReady(page, "/repositories");
    await page
      .locator('[data-testid="repositories-repo-row"][data-repo-name="daily-tech-digest"]')
      .click();
    const rows = page.locator('[data-testid="repositories-commit-row"]');
    await expect(rows).toHaveCount(15);
    // Waits for the mocked commits' own text (absent from the real snapshot) before measuring, since both the initial static snapshot and the live swap can independently satisfy `toHaveCount(15)`.
    await expect(rows.first()).toContainText("fake commit number");

    const measurements = await rows.evaluateAll((els) =>
      els.map((el) => {
        const rect = el.getBoundingClientRect();
        const lineHeight = parseFloat(getComputedStyle(el).lineHeight);
        return { height: rect.height, lineHeight };
      }),
    );
    for (const { height, lineHeight } of measurements) {
      // A clipped/overlapping row renders shorter than its own computed line-height; a full-height row never does.
      expect(height).toBeGreaterThanOrEqual(lineHeight - 0.5);
    }
  });
});

test.describe("Repositories: t is not bound", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("t from repositories does nothing — Retina-V is reachable only via Ctrl-b 3 or a click", async ({
    page,
  }) => {
    await gotoReady(page, "/repositories");
    await page.keyboard.press("t");
    await expect(page).toHaveURL(/\/repositories$/);
  });
});

test.describe("Repositories: pane frame and focus", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  const PANES = [0, 1, 2, 3, 4];

  test("clicking a repo row focuses pane 1", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await expect(paneBadge(page, 1)).not.toHaveAttribute("data-focused");
    await page.getByTestId("repositories-repo-row").first().click();
    await expect(paneBadge(page, 1)).toHaveAttribute("data-focused", "");
    await expect(paneBadge(page, 2)).not.toHaveAttribute("data-focused");
  });

  test("activating a commit focuses pane 4", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");
    await blurActive(page);
    await page.keyboard.press("1");
    await expect(paneBadge(page, 4)).not.toHaveAttribute("data-focused");
    await page.getByTestId("repositories-commit-row").first().click();
    await expect(paneBadge(page, 4)).toHaveAttribute("data-focused", "");
    await expect(paneBadge(page, 1)).not.toHaveAttribute("data-focused");
  });

  test("every pane keeps the same hairline whichever pane is focused", async ({ page }) => {
    await gotoReady(page, "/repositories");
    for (const key of ["0", "4"]) {
      await page.keyboard.press(key);
      await expect(paneBadge(page, Number(key))).toHaveAttribute("data-focused", "");
      for (const n of PANES) {
        const pane = page.getByTestId(`repositories-panel-${n}`);
        await expect(pane).toHaveCSS("border", "1px solid rgba(224, 69, 60, 0.3)");
        await expect(pane).toHaveCSS("border-radius", "4px");
      }
    }
  });

  test("no pane draws a shadow", async ({ page }) => {
    await gotoReady(page, "/repositories");
    for (const n of PANES) {
      await expect(page.getByTestId(`repositories-panel-${n}`)).toHaveCSS("box-shadow", "none");
    }
  });

  test("panes under a full badge pad 19px on top; the status pane pads 10px", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await expect(page.getByTestId("repositories-panel-0")).toHaveCSS("padding-top", "10px");
    for (const n of [1, 2, 3, 4]) {
      await expect(page.getByTestId(`repositories-panel-${n}`)).toHaveCSS("padding-top", "19px");
    }
  });

  test("pane 2 stays inside its column and scrolls its file list", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "Data-Structures-And-Algorithms");
    const list = page.getByTestId("repositories-files-list");
    await expect(list).toHaveCSS("overflow-y", "auto");
    // The deep tree must genuinely overflow, or containment would hold even without the pane's min-height:0.
    expect(await list.evaluate((el) => el.scrollHeight > el.clientHeight)).toBe(true);
    const pane = await page.getByTestId("repositories-panel-2").boundingBox();
    const column = await page.getByTestId("repositories-panel-2").locator("xpath=..").boundingBox();
    expect(pane).toBeTruthy();
    expect(column).toBeTruthy();
    if (pane && column) {
      expect(pane.y + pane.height).toBeLessThanOrEqual(column.y + column.height);
    }
  });

  test("no badge is focused while a split shell pane holds focus", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await ctrlB(page);
    await page.keyboard.press("|");
    await expect(page.getByTestId("pane-leaf")).toHaveCount(2);
    await expect(
      page.getByTestId("pane-leaf").and(page.locator('[data-pane-focused="true"]')),
    ).toHaveCount(1);
    await expect(page.getByTestId("panel-badge").and(page.locator("[data-focused]"))).toHaveCount(
      0,
    );
  });
});

// Regression guard: every row keeps a transparent 2px gutter, so selecting a row must never move its text.
test.describe("Repositories: selecting a row never shifts its text", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("a repo row's mark keeps its x when the row is selected", async ({ page }) => {
    await gotoReady(page, "/repositories");
    const row = page.getByTestId("repositories-repo-row").nth(1);
    const mark = row.getByTestId("repositories-repo-mark");
    await expectUnselectedRow(row);
    const before = await leftOf(mark);

    await page.keyboard.press("1");
    await page.keyboard.press("ArrowDown");
    await expect(row).toHaveCSS("color", SELECTED_TEXT);
    expect(await leftOf(mark)).toBe(before);
  });

  test("a tree row's icon keeps its x when the row is selected", async ({ page }) => {
    await gotoReady(page, "/repositories");
    const row = page.getByTestId("repositories-tree-row").nth(1);
    const icon = row.getByTestId("repositories-tree-icon");
    await expectUnselectedRow(row);
    const before = await leftOf(icon);

    await page.keyboard.press("ArrowDown");
    await expect(row).toHaveCSS("color", SELECTED_TEXT);
    expect(await leftOf(icon)).toBe(before);
  });
});

test.describe("Repositories: list scrollers fade their bottom edge", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  const SCROLLERS = [
    "repositories-repos-list",
    "repositories-files-list",
    "repositories-commits-list",
  ];

  test("the repos, files and commits lists mask their bottom 16px", async ({ page }) => {
    await gotoReady(page, "/repositories");
    for (const id of SCROLLERS) {
      await expect(page.getByTestId(id)).toHaveCSS(
        "mask-image",
        /linear-gradient.*calc\(100% - 16px\)/,
      );
    }
  });

  // Regression guard: the masked lists stay vertical scrollers.
  test("the masked lists still scroll vertically", async ({ page }) => {
    await gotoReady(page, "/repositories");
    for (const id of SCROLLERS) {
      await expect(page.getByTestId(id)).toHaveCSS("overflow-y", "auto");
    }
  });

  // Regression guard: the mask does not swallow wheel scrolling.
  test("the files list still wheel-scrolls under the fade", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "Data-Structures-And-Algorithms");
    const list = page.getByTestId("repositories-files-list");
    await expect.poll(() => list.evaluate((el) => el.scrollHeight > el.clientHeight)).toBe(true);
    const before = await list.evaluate((el) => el.scrollTop);

    await list.hover();
    await page.mouse.wheel(0, 400);
    await expect.poll(() => list.evaluate((el) => el.scrollTop)).toBeGreaterThan(before);
  });

  // Regression guard: only the list scrollers are masked.
  test("the content body, pane boxes and rows have no mask", async ({ page }) => {
    await gotoReady(page, "/repositories");
    await expect(page.getByTestId("repositories-changes-body")).toHaveCSS("mask-image", "none");
    for (const n of [1, 2, 4]) {
      await expect(page.getByTestId(`repositories-panel-${n}`)).toHaveCSS("mask-image", "none");
    }
    await expect(page.getByTestId("repositories-repo-row").first()).toHaveCSS("mask-image", "none");
    await expect(page.getByTestId("repositories-tree-row").first()).toHaveCSS("mask-image", "none");
  });
});

test.describe("Repositories: client-side commit refresh (panel [1] selection only)", () => {
  // daily-tech-digest isn't the default selection, so every test here explicitly selects it to match its committed snapshot head, loaded (not hardcoded) from `dailyTechDigestHead`.
  test("route-fulfill with a fake commit replaces the snapshot list for the selected repo", async ({
    page,
  }) => {
    const fakeCommit = {
      sha: "deadbeef00001111222233334444555566667777",
      commit: { message: "fake live commit for e2e\n\nbody text", author: { name: "Test Bot" } },
      author: { login: "TestBot" },
      html_url:
        "https://github.com/ShevinuM/daily-tech-digest/commit/deadbeef00001111222233334444555566667777",
    };
    await page.route("**/api.github.com/**", (route) => route.abort());
    await page.route("**/api.github.com/repos/ShevinuM/daily-tech-digest/commits**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify([fakeCommit]),
      }),
    );

    await gotoReady(page, "/repositories");
    await page
      .locator('[data-testid="repositories-repo-row"][data-repo-name="daily-tech-digest"]')
      .click();
    await expect
      .poll(
        async () =>
          page.locator('[data-testid="repositories-commit-row"]').first().getAttribute("data-sha8"),
        {
          timeout: 5000,
        },
      )
      .toBe("deadbeef");
  });

  test("route-abort keeps the committed snapshot list intact", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) => route.abort());
    await gotoReady(page, "/repositories");
    await page
      .locator('[data-testid="repositories-repo-row"][data-repo-name="daily-tech-digest"]')
      .click();
    await page.waitForTimeout(500);
    await expect(page.locator('[data-testid="repositories-commit-row"]').first()).toHaveAttribute(
      "data-sha8",
      dailyTechDigestHead.sha8,
    );
  });

  test("API 403 keeps the committed snapshot list intact", async ({ page }) => {
    await page.route("**/api.github.com/**", (route) =>
      route.fulfill({
        status: 403,
        contentType: "application/json",
        body: JSON.stringify({ message: "API rate limit exceeded" }),
      }),
    );
    await gotoReady(page, "/repositories");
    await page
      .locator('[data-testid="repositories-repo-row"][data-repo-name="daily-tech-digest"]')
      .click();
    await page.waitForTimeout(500);
    await expect(page.locator('[data-testid="repositories-commit-row"]').first()).toHaveAttribute(
      "data-sha8",
      dailyTechDigestHead.sha8,
    );
  });
});

test.describe("Repositories: editor statusline stays a single line", () => {
  test.beforeEach(async ({ context }) => {
    await context.route("**/api.github.com/**", (route) => route.abort());
  });

  test("statusline height is identical for a short breadcrumb and a long nested-path breadcrumb", async ({
    page,
  }) => {
    // Viewport narrowed just enough to force the long breadcrumb to overflow (below 900px the desktop keyboard-listener gate never attaches) — only the breadcrumb's own ellipsis/nowrap CSS keeps this single-line.
    await page.setViewportSize({ width: 900, height: 700 });
    await gotoReady(page, "/repositories");
    await openRepoTree(page, "daily-tech-digest");

    // Short baseline: "daily-tech-digest › README.md" at depth 0 — needs disambiguating since daily-tech-digest also has a nested "site/README.md".
    await treeRow(page, "README.md", 0).click();
    await page.keyboard.press("2");
    await page.keyboard.press("Enter");
    const statusline = page.locator('[data-testid="editor-statusline"]');
    await expect(statusline).toBeVisible();
    const shortHeight = (await statusline.boundingBox())!.height;

    await page.keyboard.press(":");
    await page.keyboard.type("q");
    await page.keyboard.press("Enter");
    await expect(page.locator('[data-testid="editor-scroller"]')).toHaveCount(0);

    // Long breadcrumb: Data-Structures-And-Algorithms' longest real path (read off disk so it can't drift) — its 61-char filename alone exceeds the available flex space at any allowed viewport width, forcing overflow reliably.
    const longFileName = "avaerage_salary_excluding_the_minimum_and_maximum_salary.py";
    const longPath = `Sorting Algorithms/${longFileName}`;
    expect(fileLines(`Data-Structures-And-Algorithms/${longPath}`).length).toBeGreaterThan(0);
    await openRepoTree(page, "Data-Structures-And-Algorithms");
    await treeRow(page, longFileName).click();
    await page.keyboard.press("2");
    await page.keyboard.press("Enter");
    await expect(statusline).toBeVisible();
    const longHeight = (await statusline.boundingBox())!.height;

    // Equal height (within a hairline of rounding) proves the long-path
    // breadcrumb truncated/ellipsized instead of wrapping onto a 2nd line.
    expect(Math.abs(longHeight - shortHeight)).toBeLessThan(2);
  });
});
