// View-id plumbing shared by the router pages and Terminal.svelte. Not
// copy — these are internal identifiers (route paths, dashboard.yaml menu
// ids, site.yaml status-bar window ids), never rendered as text directly.
import type { ProgramName } from "../engines/tmux/tmux";

export type ViewId = "home" | "repositories" | "employment" | "retina-v" | "profile" | "help";

/** Route path for each view id — used for pushState + popstate parsing. */
export const VIEW_ROUTES: Record<ViewId, string> = {
  home: "/",
  repositories: "/repositories",
  employment: "/employment",
  "retina-v": "/retina-v",
  profile: "/profile",
  help: "/help",
};

/**
 * dashboard.yaml menu rows use the prototype's original ids
 * (projects/xp/info/tracker — Homepage.dc.html `keys`/`labels`); the
 * status-bar window list (site.yaml) and our routes use the plainer
 * repositories/employment/profile/retina-v ids. This is the one place the two
 * vocabularies meet.
 */
const MENU_ID_TO_VIEW: Record<string, ViewId> = {
  projects: "repositories",
  xp: "employment",
  info: "profile",
  tracker: "retina-v",
  help: "help",
};

export function menuIdToView(menuId: string): ViewId | undefined {
  return MENU_ID_TO_VIEW[menuId];
}

export function pathToView(pathname: string): ViewId {
  const entry = (Object.entries(VIEW_ROUTES) as [ViewId, string][]).find(
    ([, path]) => path === pathname,
  );
  return entry ? entry[0] : "home";
}

/** Which status-bar window id (site.yaml) is active for a given view. Every
 * window is a real, always-listed entry (0:dashboard 1:repositories 2:employment
 * 3:retina-v 4:profile 5:help) —
 * "home" is the one ViewId whose window id doesn't match its own name. */
export function activeWindowId(view: ViewId): string {
  return view === "home" ? "dashboard" : view;
}

/** Inverse of activeWindowId's "home" special case — used by StatusBar's
 * click-to-navigate handler to turn a clicked
 * site.yaml window id back into the ViewId setView() expects. Every other
 * window id already equals its ViewId verbatim (repositories/employment/retina-v/
 * profile/help). */
export function windowIdToView(id: string): ViewId {
  return id === "dashboard" ? "home" : (id as ViewId);
}

// ---------------------------------------------------------------------------
// tmux.ts <-> ViewId bridge — the two
// vocabularies meet here, same as every other translation in this file.
// `ProgramName` (src/common/engines/tmux/tmux.ts) is what a PANE is currently running;
// `ViewId` is a ROUTE. They agree on every string except "home"/"dashboard"
// (same asymmetry activeWindowId/windowIdToView above already carry) and
// "shell" itself, which is not a route at all — a shelled-in pane freezes
// the URL wherever it already was (pushState fires only when the active
// window is a canonical program window).
// ---------------------------------------------------------------------------

export function viewIdToProgram(view: ViewId): ProgramName {
  return view === "home" ? "dashboard" : (view as ProgramName);
}

/** `null` for "shell" — the one ProgramName with no corresponding route. */
export function programToViewId(program: ProgramName): ViewId | null {
  if (program === "shell") return null;
  return program === "dashboard" ? "home" : (program as ViewId);
}

/**
 * The tmux binding that switches to `view`, e.g. "C-b 1" — looked up by
 * window id (a window's id always equals its `ProgramName`) in `windowNumbers`
 * (window id -> live tmux window number) rather than any fixed table, so it
 * always reflects the actual session state. `undefined` if that view's
 * window isn't present (e.g. it was killed).
 */
export function viewToTmuxBinding(view: ViewId, windowNumbers: Record<string, number>): string | undefined {
  const number = windowNumbers[viewIdToProgram(view)];
  return number === undefined ? undefined : `C-b ${number}`;
}

/**
 * Grep overlay Enter-routing, porting
 * Component.grepOpenRow()'s path->view regex, Homepage.dc.html lines
 * 875-878. Real-index paths (generated by scripts/generate.mjs) are
 * checked first:
 *   content/personnel|EmploymentRecords.svelte -> employment
 *   content/repositories|Repositories.svelte    -> repositories
 *   Wallpaper.svelte                           -> retina-v
 *   Profile.svelte                              -> profile
 *   else                                        -> null (close only, no navigation)
 *
 * The original port used bare, unanchored substring alternates for fixture
 * fidelity — `/xp|Yazi/i`, `/projects|Lazygit/i`,
 * `/Tracker|Wallpaper|subjects|Radar/i`, `/Profile|info/i` — which would
 * silently mis-route a *future* real path that happens to contain one of
 * those words anywhere (e.g. a hypothetical `src/lib/info.ts` matching the
 * bare `/info/i`, or an employment-adjacent `src/lib/xp-utils.ts` matching
 * `/xp/i`). Tightened below: the real-index
 * rules are segment-anchored to the exact file/dir names scripts/
 * generate.mjs actually produces, so they can only ever match the specific
 * components/content directories named above, not an incidental substring.
 *
 * The prototype's own fixture-style paths (fixtures/grep-index.json, used
 * only by the visual-regression recipes, which never press Enter — see
 * that file's own paths: src/pages/xp.astro, src/pages/projects.astro,
 * src/components/Tracker.svelte, src/components/Radar.svelte, src/content/
 * xp/*.md) use the prototype's original bare-word vocabulary instead. That
 * fallback is gated to paths OUTSIDE src/ and tests/ — every fixture path
 * above lives under src/, so this fallback is unreachable for any of them
 * (this file's own root-level fixture entries like
 * README.md/package.json/astro.config.mjs don't match the legacy words
 * either, so the fallback is effectively inert dead code, kept only for
 * prototype-regex fidelity) — the real rules above always run first and
 * unconditionally own everything under src/ and tests/, so no future real
 * file added there can ever fall through to the bare-word fallback.
 */
export function grepPathToView(path: string): ViewId | null {
  if (/(^|\/)content\/personnel\/|(^|\/)EmploymentRecords\.svelte$/.test(path)) return "employment";
  if (/(^|\/)content\/repositories\/|(^|\/)Repositories\.svelte$/.test(path)) return "repositories";
  if (/(^|\/)Wallpaper\.svelte$/.test(path)) return "retina-v";
  if (/(^|\/)Profile\.svelte$/.test(path)) return "profile";

  if (!/^(src|tests)\//.test(path)) {
    if (/projects|Lazygit/.test(path)) return "repositories";
    if (/xp|Yazi/.test(path)) return "employment";
    if (/Tracker|Radar|subjects/.test(path)) return "retina-v";
    if (/info/i.test(path)) return "profile";
  }
  return null;
}
