// Anti-drift guard for the fixture all-projects index.
// `fixtures/repos/all-projects.json` is HAND-COMMITTED (not
// regenerated by `pnpm generate`, which only ever touches
// `public/generated/repos/all-projects.json` from the REAL
// `src/content/projects/*.md` — see scripts/generate.mjs's
// `generateAllProjectsIndex()`) so that fixture builds/goldens never couple
// to real project content ("Fixture isolation").
//
// That hand-committed file is only correct as long as it stays in exact
// sync with `fixtures/projects/*.md` — nothing enforces that automatically
// at build time, so a future edit to one of those markdown files (or an
// added/removed project) could silently desync the committed JSON from its
// own source, corrupting every visual golden and e2e assertion that reads
// the fixture "all-projects" repo without any test ever failing to say so.
//
// This test closes that gap: it rebuilds the SAME index shape IN-MEMORY
// from `fixtures/projects/*.md`, mirroring `generateAllProjectsIndex()`'s
// exact logic (one entry per `.md` file, `path` = filename verbatim, `lines`
// = the raw file text split on "\n", sorted by `path.localeCompare`), and
// asserts it deep-equals the committed `fixtures/repos/all-projects.json`
// byte-for-byte (as parsed JSON, not as text — so key ORDER never causes a
// false failure, only actual content/shape drift does). A future edit that
// forgets to regenerate the fixture JSON fails this test immediately
// instead of silently corrupting goldens.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "../..");
const FIXTURES_PROJECTS_DIR = join(ROOT, "fixtures/projects");
const FIXTURES_ALL_PROJECTS_JSON = join(ROOT, "fixtures/repos/all-projects.json");

interface RepoFile {
  path: string;
  lines: string[];
}
interface RepoIndex {
  name: string;
  files: RepoFile[];
}

/** Mirrors scripts/generate.mjs's `generateAllProjectsIndex()` exactly,
 * substituting `fixtures/projects` for `src/content/projects` — same
 * filter (`.md` files only, must be a regular file), same `{path, lines}`
 * shape, same `path.localeCompare` sort. Kept as a small local function
 * (rather than importing generate.mjs's own, unexported one) since
 * scripts/generate.mjs is a standalone script with real filesystem/network
 * side effects throughout, not a module built to be imported by tests — see
 * this repo's existing precedent of hand-mirroring constants/logic across
 * the fixture/real boundary (e.g. tests/e2e/boot.spec.ts's BOOT_MS). */
function buildAllProjectsIndex(srcDir: string): RepoIndex {
  const files: RepoFile[] = [];
  for (const entry of readdirSync(srcDir)) {
    if (!entry.endsWith(".md")) continue;
    const full = join(srcDir, entry);
    if (!statSync(full).isFile()) continue;
    const content = readFileSync(full, "utf8");
    files.push({ path: entry, lines: content.split("\n") });
  }
  files.sort((a, b) => a.path.localeCompare(b.path));
  return { name: "all-projects", files };
}

test("fixtures/repos/all-projects.json exactly matches an index freshly built from fixtures/projects/*.md", () => {
  const expected = buildAllProjectsIndex(FIXTURES_PROJECTS_DIR);
  const committed = JSON.parse(readFileSync(FIXTURES_ALL_PROJECTS_JSON, "utf8")) as RepoIndex;
  assert.deepEqual(
    committed,
    expected,
    "fixtures/repos/all-projects.json is stale — regenerate it from fixtures/projects/*.md (see README's " +
      '"all-projects fixture" section) after editing any fixture project markdown file',
  );
});

test("the fixture all-projects index is non-empty and every file has non-trivial content", () => {
  const index = buildAllProjectsIndex(FIXTURES_PROJECTS_DIR);
  assert.ok(index.files.length > 0, "expected at least one fixture project .md file");
  for (const file of index.files) {
    assert.ok(file.path.endsWith(".md"), `${file.path} should be a markdown file`);
    assert.ok(file.lines.length > 1, `${file.path} should have more than one line`);
  }
});
